import {test} from 'node:test';import assert from 'node:assert/strict';
import {COURSES,questions,migrateCourse,enterUnit,battlePrompt} from '../web/course.js';
import {freshSave,createProfile,completeMission,nextChapter,reviewWord,openPack} from '../web/model.js';
import {checkSpokenSentence,startSentenceRecognition} from '../web/speech.js';
import {dailyAvailable,dailyComplete,startSoloDaily,soloDailyQuestion,answerSoloDaily,soloDailySituation,answerSoloSituation,soloDailyPhrase,finishSoloDaily} from '../web/solo-daily.js';

test('each year has 24 coherent units, 96 unique words, distinct levels and valid exercise choices',()=>{
 for(const [name,units] of Object.entries(COURSES)){assert.equal(units.length,24);assert.equal(new Set(units.flatMap(u=>u.words.map(w=>w[0]))).size,96);for(let c=0;c<24;c++){const u=units[c];assert.equal(u.words.length,4);assert.equal(u.s.length,2);assert.equal(u.r.length,2);assert.equal(u.l.length,3);assert.ok(u.story.split(' ').length>=(u.year===1?20:u.year===2?30:35));for(const w of u.words)assert.equal(w.length,3);for(let stage=0;stage<6;stage++)for(const q of questions(name,c,stage)){if(q.kind!=='learn')assert.ok(q.audio);if(q.options){assert.equal(new Set(q.options).size,q.options.length);assert.ok(q.options[q.correct]);}if(q.kind==='speaking')assert.ok(q.prompt.split(' ').length>=4);}}}
 assert.notDeepEqual(COURSES.Kai[0].words,COURSES.Tony[0].words);assert.ok(!COURSES.Kai.flatMap(u=>u.words).some(w=>w[0]==='opponent'));
});
test('course version migration preserves completed learning and global rewards',()=>{const s=freshSave();createProfile(s,'Kai',3);const p=s.profiles[s.active];p.courseVersion='old';p.chapter=4;p.done=[0,1];p.xp=40;p.cards=[25];p.packs=2;assert.ok(migrateCourse(s));assert.equal(p.xp,40);assert.equal(p.chapter,4);assert.deepEqual(p.done,[0,1]);assert.deepEqual(p.cards,[25]);assert.equal(p.packs,2);assert.equal(p.previousCourseVersion,'old');assert.equal(migrateCourse(s),false);});

test('course progression prevents repeat rewards, preserves revisit state and ends without wraparound',()=>{const s=freshSave();createProfile(s,'Tony',4);const p=s.profiles[s.active];assert.equal(enterUnit(p,2),false);for(let c=0;c<24;c++){assert.equal(p.chapter,c);for(let n=0;n<6;n++)completeMission(p,n,100000);assert.equal(nextChapter(p),true);}assert.equal(p.chapter,23);assert.equal(p.courseComplete,true);assert.equal(p.packs,24);const xp=p.xp;assert.ok(enterUnit(p,0));for(let n=0;n<6;n++)assert.equal(completeMission(p,n),false);assert.equal(p.xp,xp);assert.equal(p.packs,24);assert.ok(enterUnit(p,7));});
test('a completed map unit opens for practice even when an earlier completion record is absent',()=>{const s=freshSave();createProfile(s,'Kai',3);const p=s.profiles[s.active];p.chapter=13;p.done=[0];p.unitProgress[12]={done:[0,1,2,3,4,5],partial:{}};p.cards=[25];p.xp=87;p.packs=2;assert.equal(enterUnit(p,12),true);assert.equal(p.chapter,12);assert.deepEqual(p.done,[0,1,2,3,4,5]);assert.equal(completeMission(p,0),false);assert.equal(p.xp,87);assert.equal(p.packs,2);assert.equal(enterUnit(p,13),true);assert.equal(p.xp,87);assert.deepEqual(p.cards,[25]);assert.deepEqual(p.done,[0]);});
test('same-session repeats do not inflate spaced recall; errors remain due',()=>{const s=freshSave();createProfile(s,'Kai',3);const p=s.profiles[s.active];reviewWord(p,'borrow',true,100000);for(let i=1;i<=8;i++)reviewWord(p,'borrow',true,100000+i*1000);assert.equal(p.review.borrow.level,1);const due=p.review.borrow.due;assert.equal(due,100000+86400000);reviewWord(p,'borrow',true,due);assert.equal(p.review.borrow.level,2);reviewWord(p,'borrow',false,due+1000);assert.equal(p.review.borrow.level,0);assert.equal(p.review.borrow.due,due+1000);assert.ok(p.mistakes.includes('borrow'));});
test('battle prompts cover learned course words with plausible choices, not fixed joke distractors',()=>{for(const name of ['Kai','Tony']){const s=freshSave();createProfile(s,name,name==='Tony'?4:3);const p=s.profiles[s.active];p.chapter=3;p.battles=2;p.battle={turn:0};const seen=new Set();for(let t=0;t<16;t++){p.battle.turn=t;const q=battlePrompt(name,p);seen.add(q.word);assert.equal(q.options.length,4);assert.equal(new Set(q.options).size,4);}assert.equal(seen.size,16);}});
test('battle answer order remains stable for a turn without repeating a fixed position cycle',()=>{const s=freshSave();createProfile(s,'Kai',3);const p=s.profiles[s.active];p.chapter=3;p.battles=2;p.battle={turn:0};const positions=[];for(let turn=0;turn<24;turn++){p.battle.turn=turn;const q=battlePrompt(p.learningLevel,p);assert.deepEqual(q,battlePrompt(p.learningLevel,p));assert.deepEqual([...q.order].sort(),[0,1,2,3]);positions.push(q.order.indexOf(0));}assert.ok(new Set(positions.slice(0,8)).size>=3);assert.notDeepEqual(positions.slice(0,4),positions.slice(4,8));});
test('solo daily practice is resumable, reviews words, and pays only once per day',()=>{const s=freshSave();createProfile(s,'Kai',3);const p=s.profiles[s.active],day=new Date(2026,8,29,12).getTime();assert.equal(dailyAvailable(p),false);assert.equal(startSoloDaily(p,day),null);for(const w of COURSES.Kai[0].words)reviewWord(p,w[0],true,day-86400000);assert.equal(dailyAvailable(p),true);const plan=startSoloDaily(p,day);assert.equal(plan.words.length,3);assert.equal(startSoloDaily(p,day),plan);const first=soloDailyQuestion(p);assert.equal(answerSoloDaily(p,(first.correct+1)%4,day),false);assert.equal(plan.index,0);assert.equal(plan.misses,1);for(let i=0;i<3;i++){const q=soloDailyQuestion(p);assert.equal(new Set(q.options).size,4);assert.equal(answerSoloDaily(p,q.correct,day),true);}assert.equal(plan.index,3);const situation=soloDailySituation(p);assert.ok(situation);assert.equal(answerSoloSituation(p,(situation.correct+1)%3,day),false);assert.equal(answerSoloSituation(p,situation.correct,day),true);assert.ok(soloDailyPhrase(p));const before={xp:p.xp,packs:p.packs,cards:p.cards.length};const reward=finishSoloDaily(p,day);assert.deepEqual(reward,{shard:true,pack:false,card:null});assert.equal(dailyComplete(p,day),true);assert.equal(finishSoloDaily(p,day),null);assert.equal(p.multiplayer.shards,1);assert.deepEqual({xp:p.xp,packs:p.packs,cards:p.cards.length},before);});
test('five separate solo days earn one pack and one unowned legacy card',()=>{const s=freshSave();createProfile(s,'Kai',3);const p=s.profiles[s.active],base=new Date(2026,8,29,12).getTime();for(const w of COURSES.Kai[0].words)reviewWord(p,w[0],true,base-86400000);for(let day=0;day<5;day++){const now=base+day*86400000;startSoloDaily(p,now);for(let n=0;n<3;n++){const q=soloDailyQuestion(p);assert.equal(answerSoloDaily(p,q.correct,now),true);}const scene=soloDailySituation(p);assert.equal(answerSoloSituation(p,scene.correct,now),true);const result=finishSoloDaily(p,now);assert.ok(result);if(day===4){assert.equal(result.pack,true);assert.ok(result.card);}}assert.equal(p.packs,1);assert.equal(p.multiplayer.shards,0);assert.equal(p.soloDays,5);assert.equal(p.cards.length,1);});
test('daily review offers four distinct meanings throughout all six years',()=>{const now=new Date(2026,8,29,12).getTime();for(let year=1;year<=6;year++)for(let unit=0;unit<24;unit++){const s=freshSave();createProfile(s,'Learner',year);const p=s.profiles[s.active];p.chapter=unit;for(const w of COURSES[year][unit].words)reviewWord(p,w[0],true,now-86400000);startSoloDaily(p,now);for(let n=0;n<3;n++){const q=soloDailyQuestion(p);assert.equal(q.options.length,4,`Year ${year} unit ${unit+1}`);assert.equal(new Set(q.options).size,4,`Year ${year} unit ${unit+1}`);assert.equal(answerSoloDaily(p,q.correct,now),true);}}});
test('each unit has a distinct situation choice linked to its own useful sentence',()=>{const now=new Date(2026,8,29,12).getTime();for(let year=1;year<=6;year++)for(let unit=0;unit<24;unit++){const s=freshSave();createProfile(s,'Learner',year);const p=s.profiles[s.active];p.chapter=unit;for(const w of COURSES[year][unit].words)reviewWord(p,w[0],true,now-86400000);startSoloDaily(p,now);for(let n=0;n<3;n++){const q=soloDailyQuestion(p);answerSoloDaily(p,q.correct,now);}const situation=soloDailySituation(p);assert.equal(situation.prompt,COURSES[year][unit].l[0]);assert.ok(COURSES[year][unit].story.startsWith(situation.context));assert.equal(situation.options[situation.correct],COURSES[year][unit].s[0]);assert.equal(new Set(situation.options).size,3);}});
test('solo collection reward skips a legacy card already owned as a string id',()=>{const s=freshSave();createProfile(s,'Learner',3);const p=s.profiles[s.active],now=new Date(2026,8,29,12).getTime();p.cards=['25'];p.soloDays=4;for(const w of COURSES[3][0].words)reviewWord(p,w[0],true,now-86400000);startSoloDaily(p,now);for(let i=0;i<3;i++){const q=soloDailyQuestion(p);answerSoloDaily(p,q.correct,now);}const scene=soloDailySituation(p);assert.equal(answerSoloSituation(p,scene.correct,now),true);const reward=finishSoloDaily(p,now);assert.equal(reward.card,133);assert.deepEqual(p.cards,['25',133]);});
test('sentence matching accepts punctuation, contractions and forgiving word-order similarity',()=>{assert.ok(checkSpokenSentence('I will return it after we finish.',["I'll return it after we finish!"]).matched);assert.ok(checkSpokenSentence('We should organise the colours.', ['we should organize the colors']).matched);assert.ok(checkSpokenSentence('We greet our new classmate with a smile.', ['We greet the new classmate with smile']).matched);assert.equal(checkSpokenSentence('I can help.', ['I cannot help']).matched,false);assert.equal(checkSpokenSentence('May I borrow your pencil, please?', ['borrow pencil']).matched,false);assert.equal(checkSpokenSentence('I can help.', ['I can help and I can leave']).matched,false);});
test('sentence matching rejects meaning changes while keeping harmless recognition variants',()=>{assert.equal(checkSpokenSentence('I will return it after we finish.', ['I will not return it after we finish.']).matched,false);assert.equal(checkSpokenSentence('We should bring two books.', ['We should bring three books.']).matched,false);assert.equal(checkSpokenSentence('I will return the book tomorrow.', ['I would return the book tomorrow.']).matched,false);assert.equal(checkSpokenSentence('We can borrow a pencil after class.', ['We can lend a pencil after class.']).matched,false);assert.equal(checkSpokenSentence('We greet our new classmate with a smile.', ['We greet the new classmate with smile']).matched,true);});
test('recognition adapter advances once only, does not treat mismatch/error as success, cancels stale events',()=>{let instance;class Fake{constructor(){instance=this;}start(){}abort(){}}let matches=0;const statuses=[];const r=startSentenceRecognition({Recognition:Fake,expected:'Please return the book.',onMatch:()=>matches++,onStatus:(s,t)=>statuses.push([s,t]),onEnd:()=>{}});assert.equal(instance.lang,'en-NZ');const callback=instance.onresult;const event=text=>({resultIndex:0,results:[Object.assign([{transcript:text}],{isFinal:true})]});callback(event('Please burn the book.'));assert.equal(matches,0);assert.equal(statuses[0][0],'mismatch');callback(event('Please return the book.'));callback(event('Please return the book.'));assert.equal(matches,1);r.stop();const r2=startSentenceRecognition({Recognition:Fake,expected:'Hello there.',onMatch:()=>matches++,onStatus:()=>{},onEnd:()=>{}});const stale=instance.onresult;r2.stop();stale(event('Hello there.'));assert.equal(matches,1);});
