import {migrateSave,validSave} from './model.js';
import {migrateCourse,battlePrompt} from './course.js';
import {storageKey} from './sandbox.js';
import {byId,TYPES} from './data.js';
import {playMultiplayerBattleFX} from './battle-v3-fx.js';
import {PeerRoom} from './multiplayer-transport.js';
import {PROTOCOL,GAME,publicPlayer,validPlayer,createMatch,applyAction,questionToken,validSnapshot,alive} from './multiplayer-model.js';
import {RAID_LADDERS,RAID_STARS,createRaid,applyRaidAction,raidQuestionToken,validRaid} from './raid-model.js';
import {DUNGEON_THEMES,DUNGEON_ITEM_LABEL,createDungeon,applyDungeonAction,dungeonToken,validDungeon,createTag,applyTagAction,tagToken,validTag} from './coop-model.js';
import {initRewards,rewardResult,rewardRaid,rewardDungeon,rewardTag,validRewards,craftPack,buyCosmetic,equipCosmetic,SHOP,DISCOVERY,equippedLook,equippedTitle} from './rewards.js';
import {renderTeamPicker} from './team-picker.js';
import {activeUnit,duelPerspective,humanUnits,sideUnits,foeUnits} from './multiplayer-view.js';
const test=new URLSearchParams(location.search).get('test')==='1',key=storageKey(test),sessionKey='pocket-together-session:'+key,root=document.querySelector('#together');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(text,action,extra='')=>`<button data-mp="${action}" ${extra}>${text}</button>`;
const TWO=['raid','dungeon','tag'];
let saved,profileId,room=null,lobby={},match=null,acks=[],lastSeen={},selection=[],side=0,error='',busy=false,pending=false,animation=null,lastSignature='',lastHello=0,filter='',pauseSince=0,playMode='duel',raidLadder='electric',raidStar=1,dungeonTheme='forest',resumeGrace=0,networkDebug=[];
function read(){const s=JSON.parse(localStorage.getItem(key)||'null');if(!s)throw Error('먼저 일반 게임 또는 부모 테스트에서 프로필을 만들어 주세요.');migrateSave(s);migrateCourse(s);Object.values(s.profiles||{}).forEach(initRewards);if(!validSave(s)||!Object.values(s.profiles).every(validRewards))throw Error('백업을 확인해 주세요. 저장 기록은 변경하지 않았습니다.');return s;}
function profile(){return saved.profiles[profileId];}
function writeProfile(p){const latest=read();if(!latest.profiles[profileId])throw Error('프로필이 변경됐어요. 다시 입장해 주세요.');latest.profiles[profileId]=p;try{localStorage.setItem(key,JSON.stringify(latest));}catch{throw Error('저장 공간을 확인하고 다시 연결해 주세요.');}saved=latest;}
function selectProfile(id){profileId=id;const p=structuredClone(saved.profiles[id]);initRewards(p);writeProfile(p);selection=[...new Set(p.cards.map(String))].filter(id=>byId(id)?.battleEligible!==false).slice(0,3).map(id=>byId(id).id);}
function keep(){if(!room)return;try{sessionStorage.setItem(sessionKey,JSON.stringify({credentials:room.credentials(),profileId,lobby,match,acks,selection,side,pauseSince,playMode,raidLadder,raidStar,dungeonTheme,at:Date.now()}));}catch{error=error||'이 탭의 복귀 정보를 저장하지 못했어요.';}}
const envelope=(type,payload={})=>({protocol:PROTOCOL,game:GAME,room:room.code,type,...payload});
function publish(){if(!room?.isHost)return;room.broadcast(envelope('snapshot',{lobby,match,acks,session:{playMode,raidLadder,raidStar,dungeonTheme}}));keep();render();}
function mine(){return match?.players.find(p=>p.id===profile().multiplayer.id);}
function pay(latest){return match.mode==='raid'?rewardRaid(latest,match):match.mode==='dungeon'?rewardDungeon(latest,match):match.mode==='tag'?rewardTag(latest,match):rewardResult(latest,match);}
function takeReward(){if(!match||match.phase!=='end'||match.winner==='abandoned')return;try{const latest=read().profiles[profileId],next=pay(latest);if(next)writeProfile(next);const cur=next||latest;if(cur.multiplayer.ledger.some(r=>r.id===match.id)){if(room.isHost){if(!acks.includes(room.id))acks.push(room.id);}else room.send(room.host,envelope('reward_ack',{matchId:match.id}));}error='';}catch{error='보상 저장을 완료하지 못했어요. 저장 공간을 확인하고 다시 연결해 주세요.';}}
function validIncoming(m){return m?.mode==='raid'?validRaid(m):m?.mode==='dungeon'?validDungeon(m):m?.mode==='tag'?validTag(m):validSnapshot(m);}
function applyCmd(state,cmd){return state?.mode==='raid'?applyRaidAction(state,cmd):state?.mode==='dungeon'?applyDungeonAction(state,cmd):state?.mode==='tag'?applyTagAction(state,cmd):applyAction(state,cmd);}
function receive(from,msg){if(msg?.protocol!==PROTOCOL||msg.game!==GAME){error='Both devices need the same game version.';render();return;}if(msg.room!==room.code)return;lastSeen[from]=Date.now();
 if(room.isHost){
  if(msg.type==='hello'){
   if(msg.test!==test){error='일반 게임과 부모 테스트 모드를 서로 연결할 수 없어요.';render();return;}
   if(!validPlayer(msg.player)||Object.entries(lobby).some(([id,e])=>id!==from&&e.player.id===msg.player.id))return;
   if(!match){const previous=lobby[from];lobby[from]={player:msg.player,ready:previous?.ready&&JSON.stringify(previous.player)===JSON.stringify(msg.player)};}publish();
  }else if(msg.type==='ready'&&!match&&lobby[from]){lobby[from].ready=msg.ready===true;publish();}
  else if(msg.type==='action'&&lobby[from]&&msg.action?.playerId===lobby[from].player.id)dispatch(msg.action);
  else if(msg.type==='reward_ack'&&match?.phase==='end'&&msg.matchId===match.id&&lobby[from]){if(!acks.includes(from)){acks.push(from);publish();}}
 }else if(from===room.host&&msg.type==='snapshot'){
  if(!msg.lobby||Object.keys(msg.lobby).length>4||!Object.values(msg.lobby).every(e=>validPlayer(e.player)))return;
  if(msg.match&&(!validIncoming(msg.match)||(match&&msg.match.id!==match.id)||(match&&msg.match.version<match.version)))return;
  if(msg.session){if(['duel','raid','dungeon','tag'].includes(msg.session.playMode))playMode=msg.session.playMode;if(RAID_LADDERS[msg.session.raidLadder])raidLadder=msg.session.raidLadder;if(RAID_STARS.includes(msg.session.raidStar))raidStar=msg.session.raidStar;if(DUNGEON_THEMES[msg.session.dungeonTheme])dungeonTheme=msg.session.dungeonTheme;}
  lobby=msg.lobby;acks=Array.isArray(msg.acks)?msg.acks:[];const old=match;match=msg.match;pending=false;keep();takeReward();showEvent(old);render();
 }
}
function dispatch(cmd){const old=match,n=applyCmd(match,cmd);if(!n)return;match=n;pending=false;takeReward();publish();showEvent(old);}
function act(payload){if(!match||busy||pending||match.paused)return;const cmd={protocol:PROTOCOL,game:GAME,matchId:match.id,version:match.version,playerId:profile().multiplayer.id,seq:(match.seq[profile().multiplayer.id]||0)+1,...payload};if(room.isHost)dispatch(cmd);else{pending=room.send(room.host,envelope('action',{action:cmd}));render();}}
function showEvent(old){if(!match?.event||old?.version===match.version||busy)return;const e=match.event;if(!['basic','special','team','duo'].includes(e.move))return;busy=true;render(true);const fallback=setTimeout(()=>{busy=false;animation=null;render(true);},6500);requestAnimationFrame(()=>{if(!busy){clearTimeout(fallback);return;}animation=playMultiplayerBattleFX(root,old,match,e,{onEnd(){clearTimeout(fallback);busy=false;animation=null;render(true);}});});}
function connected(){return room?.isHost?room.connected():room?.connected().includes(room.host)?[room.host]:[];}
function peerStatus(id){const s=room?.peerState(id)||{};return s.connectionState==='connected'?'Relay connected':'Relay connecting…';}
function networkPanel(){if(!test||!room)return '';const ids=[...new Set([...(room.members||[]).filter(p=>p.id!==room.id).map(p=>p.id),...room.peers.keys()])];const rows=ids.map(id=>{const member=room.members?.find(p=>p.id===id),s=room.peerState(id);return `<div><b>Relay member: ${esc(id.slice(0,8))}</b> · ${esc(peerStatus(id))}<br><small>room member: ${member?'yes':'no'} · accepted: ${member?.accepted?'yes':'no'} · envelope channel: ${s.relayState}</small></div>`}).join('');return `<details class="mp-debug" open><summary>Server relay debug</summary>${rows||'<p>Relay members not connected yet.</p>'}${networkDebug.slice(-5).map(e=>`<small>${new Date(e.at).toLocaleTimeString()} ${esc(e.id||'room')} ${esc(e.event)}</small>`).join('<br>')}</details>`;}
function pruneLobby(){if(!room?.isHost)return false;const live=new Set((room.members||[]).filter(p=>p.accepted).map(p=>p.id));live.add(room.id);let changed=false;for(const id of Object.keys(lobby))if(!live.has(id)){delete lobby[id];changed=true;}return changed;}
function gone(msg){sessionStorage.removeItem(sessionKey);room=null;lobby={};match=null;acks=[];pauseSince=0;error=msg||'방이 만료되었거나 방장이 나갔어요. 새 방을 만들어 주세요.';render(true);}
function statusTick(){if(!room)return;if(room.status==='gone'||room.closed){gone();return;}const now=Date.now();try{room.isHost?room.broadcast(envelope('ping')):room.send(room.host,envelope('ping'));}catch{}
  if(!room.isHost&&!match&&connected().length&&now-lastHello>3500&&selection.length===3){lastHello=now;try{room.send(room.host,envelope('hello',{test,player:publicPlayer(profile(),selection,side)}));}catch{}}
  if(room.isHost){if(pruneLobby()&&!match)publish();}
  if(room.isHost&&match&&match.phase!=='end'&&now>resumeGrace){
   const missing=Object.keys(lobby).filter(id=>id!==room.id&&(!connected().includes(id)||now-(lastSeen[id]||0)>8000));
   if(missing.length&&!pauseSince){pauseSince=now;match={...match,paused:true,version:match.version+1};publish();}
   else if(!missing.length&&pauseSince){pauseSince=0;match={...match,paused:false,version:match.version+1};publish();}
   else if(pauseSince&&now-pauseSince>60000){match={...match,phase:'end',winner:'abandoned',endedAt:now,version:match.version+1};publish();}
  }
  if(room.isHost&&match)publish();else if(match?.phase==='end')takeReward();render();
}
async function connect(code,resume){if(selection.length!==3)throw Error('먼저 서로 다른 포켓몬 카드 3장을 선택하세요.');room=new PeerRoom({onchange:()=>render(),onmessage:receive,onstatus:e=>{networkDebug=[...networkDebug.slice(-19),e];render(true);},onerror:e=>{if(/not found|expired|permission/i.test(e))gone(e);else{error=e;render();}}});if(resume)await room.resume(resume);else await room.open(code);
 if(test)window.__pocketTogetherDebug=()=>({members:room.members,lobby,connected:room.connected(),peers:[...room.peers.keys()].map(id=>({id,...room.peerState(id)})),events:room.debug});
 if(room.isHost&&!resume)lobby[room.id]={player:publicPlayer(profile(),selection,side),ready:false};keep();render(true);
}
function sendPlayer(){if(!room||match)return;if(room.isHost){if(lobby[room.id])lobby[room.id].ready=false;publish();}else if(connected().length)room.send(room.host,envelope('ready',{ready:false}));if(selection.length!==3)return;const player=publicPlayer(profile(),selection,side);if(room.isHost){lobby[room.id]={player,ready:false};publish();}else if(connected().length)room.send(room.host,envelope('hello',{test,player}));}
function cardArt(c,extra=''){return `<img class="card-art ${extra}" src="${esc(c.art)}" alt="${esc(c.name)}" loading="lazy">`;}
function cardThumb(id){const c=byId(id);return c?`<span class="selected-card rarity-${esc(String(c.rarity||'common').toLowerCase())}" title="${esc(c.name)}">${cardArt(c,'thumb')}<b>${esc(c.name)}</b><small>${esc(c.rarity||'Common')} · ${esc(c.power||c.move||'')}</small></span>`:'';}
function teamLabel(sideValue,mode=playMode){if(mode==='tag')return '<span class="team-badge human">HUMAN TEAM</span>';if(['duel','duo'].includes(mode))return `<span class="team-badge ${sideValue?'orange':'blue'}">${sideValue?'ORANGE TEAM':'BLUE TEAM'}</span>`;return '<span class="team-badge coop">HUMAN TEAM</span>';}
function playerState(id,entry){if(entry?.ready)return '<span class="state ready">READY</span>';const status=peerStatus(id);return `<span class="state ${status.includes('connected')?'choosing':'reconnecting'}">${status.includes('connected')?'CHOOSING':'RECONNECTING'}</span>`;}
function lobbyPlayerCard(id,entry){const p=entry.player;return `<article class="player-card side-${p.side||0}">${teamLabel(p.side)}<div class="player-card-head"><strong>${esc(p.name)}</strong>${id===room?.id?'<span class="you-tag">YOU</span>':''}</div><small>Year ${p.year}</small>${playerState(id,entry)}<div class="selected-cards">${(p.team||[]).map(c=>cardThumb(c?.id??c)).join('')}</div></article>`;}
function look(){return equippedLook(profile());}
function party(p){const me=p.id===profile().multiplayer.id;const bond=match.bondLevel>=2&&['raid','dungeon','tag'].includes(match.mode)?' · Bond Lv '+match.bondLevel:'';return `<div class="player-tile battle-player side-${p.side||0} ${match.actor===p.id?'turn':''} ${p.down?'down':''} ${me?look():''}"><div class="battle-player-head">${teamLabel(p.side,match.mode)}<b>${esc(p.name)}${me&&equippedTitle(profile())?' · '+esc(equippedTitle(profile())):''}${bond}</b>${me?'<span class="you-tag">YOU</span>':''}</div><div class="party-hp">${p.team.map(c=>`<span><em>${esc(byId(c.id).name)}</em><i><b style="width:${100*c.hp/c.max}%"></b></i><small>${c.hp}/${c.max}</small></span>`).join('')}</div></div>`;}
function rarityClasses(c){const rarity=String(c?.rarity||'common').toLowerCase().replace(/[^a-z0-9]+/g,'-'),finish=String(c?.finish||'normal').toLowerCase().replace(/[^a-z0-9]+/g,'-');return `rarity-${rarity} finish-${finish}${c?.isEx?' is-ex':''}${c?.specialArt?' is-special-art':''}`;}
function unitHp(hp,max){const pct=max?Math.max(0,Math.min(100,100*hp/max)):0;return `<div class="unit-hp"><div class="hp-track"><i style="width:${pct}%"></i></div><small>${hp}/${max} HP</small></div>`;}
function energyPips(value=0){return `<span class="unit-energy ${value>=3?'is-ready':''}" aria-label="English Power ${value} of 3">${[0,1,2].map(i=>`<i class="${value>i?'on':''}"><span>ϟ</span></i>`).join('')}</span>`;}
function typeChip(c){const t=TYPES[c.type]||TYPES.normal;return `<span class="unit-type" style="--unit-color:${esc(t.colour)}">${esc(t.symbol)} ${esc(String(c.type).toUpperCase())}</span>`;}
function unitStage(c,enemy=false){const t=TYPES[c.type]||TYPES.normal;return `<div class="unit-stage" style="--unit-color:${esc(t.colour)}"><i class="unit-aura"></i><i class="unit-ground-shadow"></i><div class="unit-mon ${enemy?'enemy-mon':'player-mon'}">${cardArt(c)}</div></div>`;}
function humanUnit(unit,{label='',position='',compact=false}={}){if(!unit)return '';const c=unit.card,me=unit.playerId===profile().multiplayer.id,t=TYPES[c.type]||TYPES.normal;return `<article class="mp-unit human-unit ${rarityClasses(c)} side-${unit.side||0} ${me?'is-me':''} ${unit.down?'is-down':''} ${compact?'is-compact':''} ${position}" data-player-id="${esc(unit.playerId)}" data-card-id="${esc(c.id)}" data-type="${esc(c.type)}" style="--unit-color:${esc(t.colour)}"><div class="unit-owner"><span>${esc(label||unit.playerName)}</span>${me?'<b>YOU</b>':''}</div>${unitStage(c,false)}<div class="unit-name"><strong>${esc(c.name)}</strong>${c.rarity?`<span>${esc(c.rarity)}</span>`:''}</div><div class="unit-skill">${typeChip(c)}<small>${esc(c.move)}</small></div>${unitHp(unit.hp,unit.max)}<div class="unit-meta">${energyPips(unit.energy)}${unit.guard?'<span class="guard-badge">SHIELD</span>':''}</div></article>`;}
function foeUnit(unit,{label='',boss=false,position=''}={}){if(!unit)return '';const c=unit.card,t=TYPES[c.type]||TYPES.normal,pid=unit.playerId?` data-player-id="${esc(unit.playerId)}"`:'';return `<article class="mp-unit foe-unit ${rarityClasses(c)} ${boss?'is-boss':''} ${position}" data-foe-id="${esc(unit.foeId)}" data-card-id="${esc(c.id)}" data-type="${esc(c.type)}"${pid} style="--unit-color:${esc(t.colour)}"><div class="unit-owner"><span>${esc(label||c.name)}</span>${boss?'<b>BOSS</b>':''}</div>${unitStage(c,true)}<div class="unit-name"><strong>${esc(c.name)}</strong>${unit.role&&unit.role!=='boss'?`<span>${esc(unit.role)}</span>`:''}</div><div class="unit-skill">${typeChip(c)}<small>${esc(c.move)}</small></div>${unitHp(unit.hp,unit.max)}${unit.shieldMax?`<div class="unit-shield"><span>SHIELD</span><i><b style="width:${100*unit.shield/unit.shieldMax}%"></b></i></div>`:''}</article>`;}
function teamGauge(label,value){const ready=value>=3;return `<div class="gauge team-gauge ${ready?'is-ready':''}"><div class="gauge-copy"><small>${esc(label)}</small><strong>${ready?'READY!':value+'/3'}</strong></div><div class="gauge-pips">${[0,1,2].map(i=>`<i class="${value>i?'on':''}"><span>${value>i?'ϟ':''}</span></i>`).join('')}</div></div>`;}
function renderDuelArena(){const {self,opponent}=duelPerspective(match,profile().multiplayer.id);if(!self||!opponent)return '';return `<div class="arena mp-arena mode-duel battle-v3 ${look()}"><div class="v3-stage-light"></div><div class="arena-mode-label"><span>OPPONENT · ${esc(opponent.playerName)}</span><b>TRAINER DUEL</b><span>${esc(self.playerName)} · MY SIDE</span></div>${foeUnit({...opponent,foeId:'opponent'},{label:opponent.playerName,position:'duel-opponent'})}<div class="vs-mark"><small>BATTLE</small>VS</div>${humanUnit(self,{label:self.playerName,position:'duel-self'})}</div>`;}
function renderDuoArena(){const blue=sideUnits(match,0),orange=sideUnits(match,1);return `<div class="arena mp-arena mode-duo battle-v3 ${look()}"><div class="v3-stage-light"></div><div class="duo-team duo-blue"><header><b>BLUE TEAM</b><span>${blue.length} TRAINERS</span></header>${blue.map((u,i)=>humanUnit(u,{label:u.playerName,position:'slot-'+i,compact:true})).join('')}</div><div class="vs-mark"><small>HUMAN</small>VS</div><div class="duo-team duo-orange"><header><b>ORANGE TEAM</b><span>${orange.length} TRAINERS</span></header>${orange.map((u,i)=>humanUnit(u,{label:u.playerName,position:'slot-'+i,compact:true})).join('')}</div></div>`;}
function renderRaidArena(){const humans=humanUnits(match),boss=foeUnits(match)[0];return `<div class="arena mp-arena mode-raid raid battle-v3 bond-lv-${match.bondLevel||1} ${look()}"><div class="v3-stage-light"></div><div class="raid-stage-title"><span>CO-OP RAID · BOND LV ${match.bondLevel||1}</span><b>★${match.star} ${esc(RAID_LADDERS[match.ladder]?.name||'Boss')} BOSS</b></div>${foeUnit(boss,{label:'RAID BOSS',boss:true,position:'raid-boss'})}<div class="coop-lineup">${humans.map((u,i)=>humanUnit(u,{label:u.playerName,position:'partner-'+i,compact:true})).join('')}</div>${teamGauge('TEAM ATTACK',match.gauge||0)}</div>`;}
function renderDungeonArena(){const humans=humanUnits(match),foe=foeUnits(match)[0],node=match.nodes?.[match.node],stage=`${Math.min((match.node||0)+1,5)}/5`;return `<div class="arena mp-arena mode-dungeon battle-v3 ${look()} ${foe?'':'dungeon-rest'}"><div class="v3-stage-light"></div><div class="dungeon-stage-title"><b>${esc(DUNGEON_THEMES[match.theme]?.name||'Dungeon')}</b><span>FLOOR ${stage} · ${esc(String(node?.type||match.phase).toUpperCase())}</span></div><div class="dungeon-route-mini">${match.nodes.map((n,i)=>`<i class="${i<match.node?'done':i===match.node?'here':''}"><span>${i===4?'★':i+1}</span></i>`).join('')}</div>${foe?foeUnit(foe,{label:node?.type==='boss'?'DUNGEON BOSS':'ENCOUNTER',position:'dungeon-foe'}):`<div class="dungeon-event-card"><b>${match.phase==='vote'?'TREASURE CHOICE':match.phase==='quiz'?'QUIZ GATE':'TEAM REST'}</b><span>Both trainers move through the same trail.</span></div>`}<div class="coop-lineup">${humans.map((u,i)=>humanUnit(u,{label:u.playerName,position:'partner-'+i,compact:true})).join('')}</div>${foe?teamGauge('TEAM ATTACK',match.gauge||0):''}</div>`;}
function renderTagArena(){const humans=humanUnits(match),foes=foeUnits(match);return `<div class="arena mp-arena mode-tag battle-v3 ${look()}"><div class="v3-stage-light"></div><div class="tag-side tag-ai"><header><b>AI TEAM</b><span>2 AI</span></header>${foes.map((u,i)=>foeUnit(u,{label:'AI '+(i+1),position:'slot-'+i})).join('')}</div><div class="vs-mark"><small>TAG</small>VS</div><div class="tag-side tag-human"><header><b>HUMAN TEAM</b><span>2 TRAINERS</span></header>${humans.map((u,i)=>humanUnit(u,{label:u.playerName,position:'partner-'+i,compact:true})).join('')}</div>${teamGauge('TAG CHAIN',match.chain||0)}</div>`;}
function arena(){if(!match)return '';if(match.mode==='raid')return renderRaidArena();if(match.mode==='dungeon')return renderDungeonArena();if(match.mode==='tag')return renderTagArena();if(match.mode==='duo')return renderDuoArena();return renderDuelArena();}

function qToken(){const id=profile().multiplayer.id;return match.mode==='raid'?raidQuestionToken(match,id):match.mode==='dungeon'?dungeonToken(match,id):match.mode==='tag'?tagToken(match,id):questionToken(match);}
function powerMeter(value=0,label='ENGLISH POWER'){return `<div class="v3-power-meter ${value>=3?'is-ready':''}"><div><small>${esc(label)}</small><strong>${value>=3?'ATTACK READY!':value+' / 3'}</strong></div><span>${[0,1,2].map(i=>`<i class="${value>i?'on':''}">ϟ</i>`).join('')}</span></div>`;}
function promptBox(p){const q=battlePrompt(p.learningLevel,{...p,battle:{turn:match.round??match.turn??0},battles:0}),me=mine();return `${powerMeter(me?.energy||0)}<div class="v3-question-copy"><small>ANSWER TO CHARGE YOUR MOVE</small><h2>${esc(q.word)}</h2><p>Year ${p.learningLevel} · 알맞은 뜻을 고르세요.</p></div><div class="answers v3-answers">${q.order.map((i,n)=>btn(`<span>${String.fromCharCode(65+n)}</span>${esc(q.options[i])}`,'answer:'+i,busy||pending||match.paused?'disabled':'')).join('')}</div>`;}
function moveButton(card,kind,action,disabled=false,target=''){const t=TYPES[card.type]||TYPES.normal,special=kind==='special',name=special?card.power:card.move,cost=special?3:1;return btn(`<span class="move-icon" style="--move-color:${esc(t.colour)}">${esc(t.symbol)}</span><span class="move-copy"><b>${esc(name)}</b><small>${esc(String(card.type).toUpperCase())} · ⚡${cost}${target?' · '+esc(target):''}</small></span><span class="move-power">${special?'SPECIAL':'BASIC'}</span>`,action,`${disabled?'disabled':''} class="v3-move ${special?'special':''}"`);}
function coopMoves(me,disabled,extra){const card=byId(me.team[me.active].id);return `${powerMeter(me.energy)}<h2 class="v3-command-title">Choose your move</h2>${extra||''}<div class="v3-move-grid">${moveButton(card,'basic','attack:basic',me.energy<1||disabled)}${moveButton(card,'special','attack:special',me.energy<3||disabled)}${btn('<b>Guard</b><small>Reduce the next hit</small>','move:guard',`${disabled?'disabled':''} class="v3-command utility"`)}${btn('<b>Charge</b><small>Pass turn · save energy</small>','move:charge',`${disabled?'disabled':''} class="v3-command utility"`)}</div><div class="v3-switch-row"><small>SWITCH ACTIVE</small>${me.team.map((c,i)=>btn(`${cardArt(byId(c.id),'switch-thumb')}<span>${esc(byId(c.id).name)}</span>`,'switch:'+i,`${!c.hp||i===me.active||disabled?'disabled':''} class="v3-switch ${i===me.active?'is-active':''}"`)).join('')}</div>`;}
function combat(){const me=mine(),p=profile(),disabled=busy||pending||match.paused;let controls='';
 const endCopy=match.winner==='abandoned'?'연결이 복구되지 않아 종료했어요. 카드와 진도는 그대로예요.':match.mode==='raid'?(match.winner==='raiders'?'레이드 성공! 함께 해냈어요!':'아쉽게 막혔어요. 카드는 그대로예요.'):match.mode==='dungeon'?(match.winner==='clear'?'던전 클리어! 함께 걸어왔어요!':'여기서 멈췄어요. 카드는 그대로예요.'):match.mode==='tag'?(match.winner==='humans'?'Tag 승리! Duo 호흡이 맞았어요!':'좋은 대결이었어요!'):(match.winner==='draw'?'함께 끝까지 플레이했어요!':match.winner===me?.side?'우리 팀 승리!':'좋은 대결이었어요!');
 if(match.phase==='end')controls=`<h2>${endCopy}</h2><p>Adventure Medals · ${p.multiplayer.medals} 🏅 · Pack Shards ${p.multiplayer.shards} 🧩</p><p>보상 저장 확인 ${acks.length}/${match.players.length}</p>${btn('로비로','leave')}`;
 else if(match.paused)controls='<h2>Reconnecting…</h2><p>최대 60초 동안 기다립니다. 새로고침 후 이 방으로 복귀할 수 있어요.</p>';
 else if(busy)controls='<p>공격 연출 중…</p>';
 else if(match.mode==='dungeon'&&match.phase==='vote'){const n=match.nodes[match.node];controls=match.votes?.[me.id]?`<h2>친구의 선택을 기다려요</h2>`:`<h2>보물 투표</h2><p>둘 다 같은 것을 고르면 그대로, 다르면 첫 선택이 공유돼요. 한 아이만 갖지 않아요.</p>${n.options.map(i=>btn(esc(DUNGEON_ITEM_LABEL[i]||i),'vote:'+i)).join('')}`;}
 else if(match.mode==='dungeon'&&match.phase==='quiz')controls=match.answers?.[me.id]!==undefined?'<h2>친구의 답을 기다려요</h2>':`<h2>Quiz Gate</h2>${promptBox(p)}`;
 else if(['raid','dungeon','tag'].includes(match.mode)){
  const answered=match.answers?.[me?.id]!==undefined,moved=!!match.moves?.[me?.id];
  if(match.phase==='question'&&!answered)controls=`<h2>${me?.down?'Cheer · 구조 질문':match.mode==='tag'?'함께 답하면 Tag Chain':'함께 답해요'}</h2>${promptBox(p)}`;
  else if(match.phase==='question')controls='<h2>친구의 답을 기다려요</h2>';
  else if(me?.down)controls='<h2>다음 라운드를 기다려요</h2>';
  else if(moved)controls='<h2>친구의 행동을 기다려요</h2>';
  else if(match.mode==='tag'){const foes=match.foes.filter(f=>f.hp>0),card=byId(me.team[me.active].id);controls=`${powerMeter(me.energy,'ENGLISH POWER')}<div class="v3-chain-status ${match.chain>=3?'is-ready':''}"><small>TAG CHAIN</small><strong>${match.chain>=3?'TAG FINISH READY!':match.chain+' / 3'}</strong></div><h2 class="v3-command-title">Choose a target</h2><div class="v3-target-grid">${foes.map(f=>`<div class="v3-target-card"><b>AI · ${esc(byId(f.id).name)}</b><small>${f.hp}/${f.max} HP · ${esc(f.role)}</small>${moveButton(card,'basic','attack:basic:'+f.id,me.energy<1||disabled,byId(f.id).name)}${moveButton(card,'special','attack:special:'+f.id,me.energy<3||disabled,byId(f.id).name)}</div>`).join('')}</div><div class="v3-move-grid">${btn('<b>TAG FINISH</b><small>Chain 3 · both trainers strike</small>','move:duo',`${match.chain<3||disabled?'disabled':''} class="v3-command finisher"`)}${btn('<b>Guard</b><small>Reduce the next hit</small>','move:guard',`${disabled?'disabled':''} class="v3-command utility"`)}${btn('<b>Charge</b><small>Pass turn · save energy</small>','move:charge',`${disabled?'disabled':''} class="v3-command utility"`)}</div>`;}
  else controls=coopMoves(me,disabled,btn(`<b>TEAM ATTACK</b><small>${(match.gauge||0)>=3?'READY · unleash together':'Gauge '+(match.gauge||0)+'/3'}</small>`,'move:team',`${(match.gauge||0)<3||disabled?'disabled':''} class="v3-command finisher"`));
 }else{
  const active=match.players.find(p=>p.id===match.actor),myTurn=active.id===me?.id;
  if(!myTurn)controls=`<h2>${esc(active.name)}의 차례</h2><p>속도 경쟁 없이 한 사람씩 진행해요.</p>`;
  else if(match.phase==='question')controls=promptBox(p);
  else{const targets=match.players.filter(x=>x.side!==me.side&&alive(x)),card=byId(me.team[me.active].id);controls=`${powerMeter(me.energy)}<h2 class="v3-command-title">Choose your move</h2><div class="v3-target-grid">${targets.map(t=>{const tc=byId(t.team[t.active].id);return `<div class="v3-target-card"><b>${esc(t.name)} · ${esc(tc.name)}</b><small>${t.team[t.active].hp}/${t.team[t.active].max} HP</small>${moveButton(card,'basic','attack:basic:'+t.id,me.energy<1||disabled,t.name)}${moveButton(card,'special','attack:special:'+t.id,me.energy<3||disabled,t.name)}</div>`;}).join('')}</div><div class="v3-move-grid">${btn('<b>Guard</b><small>Reduce the next hit</small>','move:guard',`${disabled?'disabled':''} class="v3-command utility"`)}${btn('<b>Charge</b><small>Pass turn · save energy</small>','move:charge',`${disabled?'disabled':''} class="v3-command utility"`)}</div><div class="v3-switch-row"><small>SWITCH ACTIVE</small>${me.team.map((c,i)=>btn(`${cardArt(byId(c.id),'switch-thumb')}<span>${esc(byId(c.id).name)}</span>`,'switch:'+i,`${!c.hp||i===me.active||disabled?'disabled':''} class="v3-switch ${i===me.active?'is-active':''}"`)).join('')}</div>`;}
 }
 const title=match.mode==='raid'?`<span class="mode-kicker">CO-OP RAID</span> Raid ★${match.star} ${esc(RAID_LADDERS[match.ladder].name)} · Round ${match.round+1}`:match.mode==='dungeon'?`<span class="mode-kicker">CO-OP DUNGEON</span> Dungeon · ${esc(DUNGEON_THEMES[match.theme].name)} · ${Math.min(5,match.node+1)}/5 · ${(match.nodes[match.node]||{type:match.winner||'end'}).type}`:match.mode==='tag'?`<span class="mode-kicker">TAG BATTLE</span> HUMAN TEAM vs AI TEAM · Round ${match.round+1}`:`<span class="mode-kicker">${match.mode==='duo'?'4P HUMAN BATTLE':'1v1 HUMAN BATTLE'}</span> ${match.mode==='duo'?'BLUE TEAM vs ORANGE TEAM':'MY SIDE vs OPPONENT'} · Turn ${match.turn+1}`;
 const map=match.mode==='dungeon'?`<ol class="dungeon-map">${match.nodes.map((n,i)=>`<li class="${i===match.node?'here':i<match.node?'done':''}">${n.type}</li>`).join('')}</ol><p class="muted">Run items: ${match.items.length?match.items.join(', '):'none'}</p>`:'';
 return `<section class="battle-shell"><div class="turn-banner">${title}${match.paused?'<span class="pause-note">RECONNECTING · BATTLE PAUSED</span>':''}</div>${map}<div class="roster">${match.players.map(party).join('')}${match.mode==='tag'?match.foes.map(f=>`<div class="player-tile battle-player ai-card side-1"><div class="battle-player-head"><span class="team-badge ai">AI TEAM</span><b>AI · ${esc(byId(f.id).name)}</b></div><p>${f.hp}/${f.max} HP · ${f.role}</p></div>`).join(''):''}</div>${arena()}</section><section class="question">${controls}</section>`;
}
function starOpen(ladder,star){return star===1||(profile().multiplayer.raid?.stars?.[ladder]||0)>=star-1;}
function shopPanel(){const m=profile().multiplayer;const disc=DISCOVERY.filter(([,id])=>m.cosmetics.includes(id)).map(([n,id,name,kind])=>`<div class="shop-row"><b>${esc(name)}</b><span>Discovery ${n}</span>${btn(m.equipped[kind]===id?'착용 중':'착용','equip:'+id,m.equipped[kind]===id?'disabled':'')}</div>`).join('');return `<section class="mp-shop"><h2>Adventure Shop</h2><p>메달은 치장만 바꿉니다. 대전 숫자는 그대로예요.</p>${SHOP.map(item=>`<div class="shop-row"><b>${esc(item.name)}</b><span>${item.cost} 🏅</span>${m.cosmetics.includes(item.id)?btn(m.equipped[item.kind]===item.id?'착용 중':'착용','equip:'+item.id,m.equipped[item.kind]===item.id?'disabled':''):btn('구매','buy:'+item.id,m.medals<item.cost?'disabled':'')}</div>`).join('')}${disc}<p class="muted">Discovery ${DISCOVERY.map(([n,id,name])=>`${n} ${esc(name)}${m.cosmetics.includes(id)?' ✓':''}`).join(' · ')}</p></section>`;}
function rewardsPanel(){const m=profile().multiplayer;const bonds=Object.values(m.bond||{}).map(b=>`<div class="bond-row"><b>${esc(b.name||'Partner')}</b><span>Bond Lv ${b.level} · ${b.xp} XP</span><i><b style="width:${Math.min(100,b.level>=5?100:(b.xp%3)/3*100)}%"></b></i></div>`).join('');return `<section class="mp-rewards"><h2>Adventure Rewards</h2><p>${m.medals} 🏅 Medals · ${m.shards} / 5 🧩 Pack Shards · 승 ${m.wins} / 패 ${m.losses}</p>${bonds?`<div class="team-bonds"><h3>Team Bond</h3>${bonds}</div>`:''}${m.shards>=5?btn('조각 5개로 팩 1개 만들기','craft'):'<p class="muted">레이드·던전·태그 각각 하루 첫 성공마다 조각 1개. PVP는 0.</p>'}${Object.keys(m.raid?.stars||{}).length?`<p>레이드 별: ${Object.entries(m.raid.stars).map(([k,v])=>esc(RAID_LADDERS[k]?.name||k)+' ★'+v).join(' · ')}</p>`:''}${m.badges?.length?`<p>배지 ${m.badges.length} · 코스메틱 ${m.cosmetics.length}</p>`:''}</section>`+shopPanel();}
function modeHelp(){return {duel:'2명이면 1대1, 4명이면 실제 사람 2대2입니다.',raid:'실제 두 명이 한 보스를 함께 공략합니다. 2 humans vs 2 AI가 아닙니다.',dungeon:'두 명이 같은 지도를 걷습니다. 보물은 함께 고르고, 아이템은 이번 탐험에서만 씁니다.',tag:'두 명이 2 AI와 태그합니다. 4인 사람 대전은 Duel 2v2를 쓰세요.'}[playMode];}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&room)room.tick().catch(e=>{error=e.message;render(true);});});
function render(force=false){if(busy&&!force)return;const signature=JSON.stringify([profileId,room?.code,room?.members,connected(),lobby,match,acks,selection,side,error,pending,busy,filter,playMode,raidLadder,raidStar,dungeonTheme]);if(!force&&signature===lastSignature)return;lastSignature=signature;
 const p=profile();if(p)root.className='together '+look();
 const heading=`<header><h1>Together <small>Battle V3</small></h1>${room?(room.isHost?btn('참가자 새로고침','refresh'):'')+btn('방 나가기','leave'):`<a href="./${test?'?test=1':''}">게임으로 돌아가기</a>`}</header><p class="status" role="status">${error?'<span class="error">'+esc(error)+'</span>':room?'연결 '+connected().length+' · '+(test?'부모 테스트 전용':'일반 기록'):'카드를 잃지 않는 친구 대결 · 최대 4명 · 협동 2인'}</p>${networkPanel()}`;
 if(!p){root.innerHTML=heading+'<section>먼저 게임에서 프로필을 만들어 주세요.</section>';return;}
 if(match){root.innerHTML=heading+combat();return;}
 const owned=[...new Set(p.cards.map(String))].map(byId).filter(c=>c?.battleEligible!==false&&c);const available=owned.filter(c=>c.name.toLowerCase().includes(filter.toLowerCase()));
 const hostLock=room&&!room.isHost,need=TWO.includes(playMode)?2:null;
 const picker=renderTeamPicker({cards:owned,selected:selection,max:3,action:'card',filter,inputId:'mp-filter',label:'YOUR TEAM',button:(content,actionName,attrs)=>btn(content,actionName,attrs)});
 root.innerHTML=heading+`<section class="mp-modes"><p>모드 ${[['duel','Trainer Duel'],['raid','Boss Raid · 2인'],['dungeon','Dungeon · 2인'],['tag','Tag vs 2 AI']].map(([id,label])=>btn(label,'mode:'+id,`aria-pressed="${playMode===id}" ${hostLock?'disabled':''}`)).join('')}</p><p class="muted">${modeHelp()}</p>${playMode==='raid'?`<div class="raid-pick">${Object.entries(RAID_LADDERS).map(([id,l])=>btn(l.name,'ladder:'+id,`aria-pressed="${raidLadder===id}" ${hostLock?'disabled':''}`)).join('')}</div><div class="raid-pick">${RAID_STARS.map(n=>btn('★'.repeat(n),'star:'+n,`aria-pressed="${raidStar===n}" ${hostLock||!starOpen(raidLadder,n)?'disabled':''}`)).join('')}</div>`:''}${playMode==='dungeon'?`<div class="raid-pick">${Object.entries(DUNGEON_THEMES).map(([id,t])=>btn(t.name,'theme:'+id,`aria-pressed="${dungeonTheme===id}" ${hostLock?'disabled':''}`)).join('')}</div>`:''}</section>`+rewardsPanel()+`<section><label>Trainer <select id="mp-profile" ${room?'disabled':''}>${Object.entries(saved.profiles).map(([id,p])=>`<option value="${id}" ${id===profileId?'selected':''}>${esc(p.displayName)} · Year ${p.learningLevel}</option>`).join('')}</select></label><p>${p.multiplayer.medals} 🏅 · 세 장을 골라 주세요 (${selection.length}/3).</p>${playMode==='duel'?`<p>팀 ${btn('Blue','side:0',`aria-pressed="${side===0}"`)}${btn('Orange','side:1',`aria-pressed="${side===1}"`)}</p>`:''}${picker}${owned.length<3?'<p>학습으로 팩을 얻어 포켓몬 3종을 모으면 참가할 수 있어요. 부모 테스트에서는 바로 체험할 수 있어요.</p>':''}</section>`;
 if(!room)root.innerHTML+=`<section><h2>친구와 만나기</h2>${btn('Create room · 방 만들기','create')}<label>Room code <input id="mp-code" maxlength="6" autocomplete="off" placeholder="ABC123"></label>${btn('Join room · 참가','join')}<p class="mp-help">같은 테스트 서버에 접속한 기기끼리 연결합니다. 방장은 참가 요청을 승인해 주세요. 공식 사이트는 변경하지 않는 미리보기입니다.</p></section>`;
 else{const entries=Object.entries(lobby),members=(room.members||[]).filter(p=>p.id!==room.id&&p.accepted),pending=members.filter(p=>!lobby[p.id]).map(p=>`<article class="player-card pending-card"><strong>JOIN REQUEST · ${esc(p.id.slice(0,6))}</strong><span class="state reconnecting">${peerStatus(p.id)}</span><p>Waiting for host approval</p></article>`).join(''),shown=Math.max(entries.length+pending.length,1),expected=TWO.includes(playMode)?2:(entries.length===4?4:2),allReady=entries.length===expected&&entries.every(([id,p])=>p.ready&&(id===room.id||connected().includes(id))),balanced=playMode!=='duel'||(entries.filter(([,v])=>v.player.side===0).length===expected/2&&entries.filter(([,v])=>v.player.side===1).length===expected/2),canStart=allReady&&balanced;root.innerHTML+=`<section class="lobby-panel"><h2>Room <span class="room-code">${room.code}</span></h2><p class="lobby-summary">${shown}${need?'/'+need:''} players${playMode==='duel'?` · <b>MY SIDE</b> ${entries.filter(([,v])=>v.player.side===0).length} Blue / <b>OPPONENT</b> ${entries.filter(([,v])=>v.player.side===1).length} Orange · ${entries.length===4?'4 HUMAN PLAYERS · 2v2':'1v1'}`:' · HUMAN TEAM · 2-player co-op'}</p><div class="player-grid">${entries.map(([id,v])=>lobbyPlayerCard(id,v)).join('')}${pending}</div>${room.isHost?btn('Refresh participants','refresh'):''}${btn(lobby[room.id]?.ready?'Cancel ready':'Ready · 준비 완료','ready',selection.length!==3?'disabled':'')}${room.isHost?btn(playMode==='raid'?'Start raid':playMode==='dungeon'?'Start dungeon':playMode==='tag'?'Start tag':'Start battle · 대결 시작','start',canStart?'':'disabled'):''}<p class="muted">${TWO.includes(playMode)?'Two human players must be connected and Ready.':!balanced&&entries.length===expected?'1v1 needs 1 Blue + 1 Orange. 2v2 needs 2 Blue + 2 Orange.':'1v1 is 2 players; 2v2 requires four actual human players.'}</p></section>`;}
}
function restoreFilterFocus(pos){const input=document.querySelector('#mp-filter');if(input){input.focus();if(typeof pos==='number')input.setSelectionRange(pos,pos);}}
root.addEventListener('input',e=>{if(e.target.id!=='mp-filter')return;filter=e.target.value;const pos=e.target.selectionStart;render(true);restoreFilterFocus(pos);});
root.addEventListener('change',e=>{try{if(e.target.id==='mp-profile'){selectProfile(e.target.value);filter='';render(true);}}catch(e){error=e.message;render();}});
root.addEventListener('click',async e=>{const el=e.target.closest('[data-mp]');if(!el||el.disabled)return;const [action,v,w]=el.dataset.mp.split(':');try{error='';
 if(action==='create')await connect();
 if(action==='join'){const code=document.querySelector('#mp-code')?.value.trim()||'';if(!/^[A-Za-z0-9]{6}$/.test(code))throw Error('방 코드 6자리를 확인해 주세요.');await connect(code);}
 if(action==='accept')await room.accept(v);
 if(action==='refresh'){await room.tick();render(true);}
 if(action==='card'){const c=byId(v),i=selection.findIndex(x=>String(x)===String(c.id));if(i>=0)selection.splice(i,1);else if(selection.length<3)selection.push(c.id);sendPlayer();}
 if(action==='side'){side=Number(v);sendPlayer();}
 if(action==='mode'){if(room&&!room.isHost)return;playMode=v;if(room?.isHost)publish();else render(true);}
 if(action==='ladder'){if(room&&!room.isHost)return;raidLadder=v;if(!starOpen(raidLadder,raidStar))raidStar=1;if(room?.isHost)publish();else render(true);}
 if(action==='star'){if(room&&!room.isHost)return;const n=Number(v);if(!starOpen(raidLadder,n))throw Error('이전 별을 먼저 클리어해 주세요.');raidStar=n;if(room?.isHost)publish();else render(true);}
 if(action==='theme'){if(room&&!room.isHost)return;dungeonTheme=v;if(room?.isHost)publish();else render(true);}
 if(action==='ready'){if(selection.length!==3)throw Error('카드 3장을 골라 주세요.');if(!room.isHost&&!connected().length)throw Error('연결이 끝날 때까지 기다려 주세요. 방장이 참가를 승인해야 해요.');const ready=!lobby[room.id]?.ready;sendPlayer();if(room.isHost){lobby[room.id].ready=ready;publish();}else room.send(room.host,envelope('ready',{ready}));}
 if(action==='start'){if(!room.isHost)return;const entries=Object.entries(lobby);if(!entries.every(([id,p])=>p.ready&&(id===room.id||connected().includes(id))))throw Error('모든 참가자의 연결과 Ready를 확인해 주세요.');const people=entries.map(([,p])=>p.player);if(TWO.includes(playMode)&&people.length!==2)throw Error('이 모드는 실제 사람 두 명이 필요해요.');if(playMode==='duel'&&![2,4].includes(people.length))throw Error('1대1은 2명, 2대2는 실제 사람 4명이 필요해요.');if(playMode==='duel'){const blue=people.filter(p=>p.side===0).length,orange=people.filter(p=>p.side===1).length;if(blue!==people.length/2||orange!==people.length/2)throw Error(people.length===2?'1대1은 Blue 1명 + Orange 1명이어야 해요.':'2대2는 Blue 2명 + Orange 2명이어야 해요.');}const pair=people.length===2?[people[0].id,people[1].id].sort().join(':'):'';const bondLevel=profile().multiplayer.bond?.[pair]?.level||1;match=playMode==='raid'?createRaid(people,room.code,{ladder:raidLadder,star:raidStar,bondLevel}):playMode==='dungeon'?createDungeon(people,room.code,{theme:dungeonTheme}):playMode==='tag'?createTag(people,room.code):createMatch(people,room.code);await room.request('/'+room.code+'/start',{});publish();}
 if(action==='answer')act({type:'question_result',questionToken:qToken(),correct:Number(v)===0});
 if(action==='vote')act({type:'vote',item:v});
 if(action==='attack')act({type:'battle_action',move:v,target:w});
 if(action==='move')act({type:'battle_action',move:v});
 if(action==='switch')act({type:'battle_action',move:'switch',index:Number(v)});
 if(action==='craft'){const next=craftPack(profile());if(!next)throw Error('조각 5개가 필요해요.');writeProfile(next);}
 if(action==='buy'){const next=buyCosmetic(profile(),v);if(!next)throw Error('메달이 부족하거나 이미 가지고 있어요.');writeProfile(next);}
 if(action==='equip'){const next=equipCosmetic(profile(),v);if(!next)throw Error('아직 없는 장식이에요.');writeProfile(next);}
 if(action==='leave'){animation?.cancel();if(room)await room.close().catch(()=>{});sessionStorage.removeItem(sessionKey);room=null;lobby={};match=null;acks=[];pauseSince=0;pending=false;busy=false;render(true);return;}
 keep();render();}catch(e){if(room&&!room.code){room.closed=true;room=null;}error=e.message;render(true);}});
try{saved=read();const previous=JSON.parse(sessionStorage.getItem(sessionKey)||'null');profileId=previous?.profileId||saved.active||saved.profileOrder[0];if(profileId)selectProfile(profileId);if(previous&&Date.now()-previous.at<7200000){({lobby,match,acks,selection,side,pauseSince,playMode='duel',raidLadder='electric',raidStar=1,dungeonTheme='forest'}=previous);resumeGrace=Date.now()+12000;for(const id of Object.keys(lobby||{}))lastSeen[id]=Date.now();try{await connect(null,previous.credentials);if(room.isHost)publish();}catch{sessionStorage.removeItem(sessionKey);room=null;lobby={};match=null;error='이전 방을 찾지 못했어요. 새 방을 만들어 주세요.';}}render(true);setInterval(statusTick,2000);}catch(e){error=e.message;root.innerHTML=`<h1>Together</h1><p class="error">${esc(error)}</p><a href="./${test?'?test=1':''}">게임으로 돌아가기</a>`;}
