import {migrateSave,validSave} from './model.js';
import {migrateCourse,battlePrompt} from './course.js';
import {storageKey} from './sandbox.js';
import {byId} from './data.js';
import {battleSequence} from './cinematic.js';
import {PeerRoom} from './multiplayer-transport.js';
import {PROTOCOL,GAME,publicPlayer,validPlayer,createMatch,applyAction,questionToken,validSnapshot,alive} from './multiplayer-model.js';
import {RAID_LADDERS,RAID_STARS,createRaid,applyRaidAction,raidQuestionToken,validRaid} from './raid-model.js';
import {DUNGEON_THEMES,DUNGEON_ITEM_LABEL,createDungeon,applyDungeonAction,dungeonToken,validDungeon,createTag,applyTagAction,tagToken,validTag} from './coop-model.js';
import {initRewards,rewardResult,rewardRaid,rewardDungeon,rewardTag,validRewards,craftPack,buyCosmetic,equipCosmetic,SHOP,DISCOVERY,equippedLook,equippedTitle} from './rewards.js';
const test=new URLSearchParams(location.search).get('test')==='1',key=storageKey(test),sessionKey='pocket-together-session:'+key,root=document.querySelector('#together');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(text,action,extra='')=>`<button data-mp="${action}" ${extra}>${text}</button>`;
const TWO=['raid','dungeon','tag'];
let saved,profileId,room=null,lobby={},match=null,acks=[],lastSeen={},selection=[],side=0,error='',busy=false,pending=false,animation=null,lastSignature='',lastHello=0,filter='',pauseSince=0,playMode='duel',raidLadder='electric',raidStar=1,dungeonTheme='forest',resumeGrace=0,networkDebug=[];
function read(){const s=JSON.parse(localStorage.getItem(key)||'null');if(!s)throw Error('먼저 일반 게임 또는 부모 테스트에서 프로필을 만들어 주세요.');migrateSave(s);migrateCourse(s);Object.values(s.profiles||{}).forEach(initRewards);if(!validSave(s)||!Object.values(s.profiles).every(validRewards))throw Error('백업을 확인해 주세요. 저장 기록은 변경하지 않았습니다.');return s;}
function profile(){return saved.profiles[profileId];}
function writeProfile(p){const latest=read();if(!latest.profiles[profileId])throw Error('프로필이 변경됐어요. 다시 입장해 주세요.');latest.profiles[profileId]=p;try{localStorage.setItem(key,JSON.stringify(latest));}catch{throw Error('저장 공간을 확인하고 다시 연결해 주세요.');}saved=latest;}
function selectProfile(id){profileId=id;const p=structuredClone(saved.profiles[id]);initRewards(p);writeProfile(p);selection=[...new Set(p.cards.map(String))].filter(id=>byId(id)?.battleEligible!==false).slice(0,3).map(id=>byId(id).id);}
function keep(){if(!room)return;try{sessionStorage.setItem(sessionKey,JSON.stringify({credentials:room.credentials(),profileId,lobby,match,acks,selection,side,pauseSince,playMode,raidLadder,raidStar,dungeonTheme,at:Date.now()}));}catch{error=error||'이 탭의 복귀 정보를 저장하지 못했어요.';}}
const envelope=(type,payload={})=>({protocol:PROTOCOL,game:GAME,room:room.code,type,...payload});
function publish(){if(!room?.isHost)return;room.broadcast(envelope('snapshot',{lobby,match,acks,session:{playMode,raidLadder,raidStar,dungeonTheme}}));keep();render();}
function mine(){return match?.players.find(p=>p.id===profile().multiplayer.id);}
function pay(latest){return match.mode==='raid'?rewardRaid(latest,match):match.mode==='dungeon'?rewardDungeon(latest,match):match.mode==='tag'?rewardTag(latest,match):rewardResult(latest,match);}
function takeReward(){if(!match||match.phase!=='end'||match.winner==='abandoned')return;try{const latest=read().profiles[profileId],next=pay(latest);if(next)writeProfile(next);const cur=next||latest;if(cur.multiplayer.ledger.some(r=>r.id===match.id)){if(room.isHost){if(!acks.includes(room.id))acks.push(room.id);}else room.send(room.host,envelope('reward_ack',{matchId:match.id}));}error='';}catch{error='보상 저장을 완료하지 못했어요. 저장 공간을 확인하고 다시 연결해 주세요.';}}
function validIncoming(m){return m?.mode==='raid'?validRaid(m):m?.mode==='dungeon'?validDungeon(m):m?.mode==='tag'?validTag(m):validSnapshot(m);}
function applyCmd(state,cmd){return state?.mode==='raid'?applyRaidAction(state,cmd):state?.mode==='dungeon'?applyDungeonAction(state,cmd):state?.mode==='tag'?applyTagAction(state,cmd):applyAction(state,cmd);}
function receive(from,msg){if(msg?.protocol!==PROTOCOL||msg.game!==GAME){error='Both devices need the same game version.';render();return;}if(msg.room!==room.code)return;lastSeen[from]=Date.now();
 if(room.isHost){
  if(msg.type==='hello'){
   if(msg.test!==test){error='일반 게임과 부모 테스트 모드를 서로 연결할 수 없어요.';render();return;}
   if(!validPlayer(msg.player)||Object.entries(lobby).some(([id,e])=>id!==from&&e.player.id===msg.player.id))return;
   if(!match){const previous=lobby[from];lobby[from]={player:msg.player,ready:previous?.ready&&JSON.stringify(previous.player)===JSON.stringify(msg.player)};}publish();
  }else if(msg.type==='ready'&&!match&&lobby[from]){lobby[from].ready=msg.ready===true;publish();}
  else if(msg.type==='action'&&lobby[from]&&msg.action?.playerId===lobby[from].player.id)dispatch(msg.action);
  else if(msg.type==='reward_ack'&&match?.phase==='end'&&msg.matchId===match.id&&lobby[from]){if(!acks.includes(from)){acks.push(from);publish();}}
 }else if(from===room.host&&msg.type==='snapshot'){
  if(!msg.lobby||Object.keys(msg.lobby).length>4||!Object.values(msg.lobby).every(e=>validPlayer(e.player)))return;
  if(msg.match&&(!validIncoming(msg.match)||(match&&msg.match.id!==match.id)||(match&&msg.match.version<match.version)))return;
  if(msg.session){if(['duel','raid','dungeon','tag'].includes(msg.session.playMode))playMode=msg.session.playMode;if(RAID_LADDERS[msg.session.raidLadder])raidLadder=msg.session.raidLadder;if(RAID_STARS.includes(msg.session.raidStar))raidStar=msg.session.raidStar;if(DUNGEON_THEMES[msg.session.dungeonTheme])dungeonTheme=msg.session.dungeonTheme;}
  lobby=msg.lobby;acks=Array.isArray(msg.acks)?msg.acks:[];const old=match;match=msg.match;pending=false;keep();takeReward();showEvent(old);render();
 }
}
function dispatch(cmd){const old=match,n=applyCmd(match,cmd);if(!n)return;match=n;pending=false;takeReward();publish();showEvent(old);}
function act(payload){if(!match||busy||pending||match.paused)return;const cmd={protocol:PROTOCOL,game:GAME,matchId:match.id,version:match.version,playerId:profile().multiplayer.id,seq:(match.seq[profile().multiplayer.id]||0)+1,...payload};if(room.isHost)dispatch(cmd);else{pending=room.send(room.host,envelope('action',{action:cmd}));render();}}
function showEvent(old){if(!match?.event||old?.version===match.version||busy)return;const e=match.event;if(!['basic','special','team','duo'].includes(e.move))return;busy=true;render(true);const me=byId(e.own),foe=byId(e.foe);const before={team:[{id:me.id,hp:me.hp}],enemies:[{id:foe.id,hp:e.before,max:e.max}],active:0,enemy:0};const after=structuredClone(before);after.enemies[0].hp=e.after;animation=battleSequence(root,before,after,e.move==='basic'?'basic':'special',{effects:saved.effects,onEnd(){busy=false;animation=null;render(true);}});}
function connected(){return room?.isHost?room.connected():room?.connected().includes(room.host)?[room.host]:[];}
function peerStatus(id){const s=room?.peerState(id)||{};if(s.dataChannelState==='open'||s.connectionState==='connected')return 'Connected / Ready';if(['failed','closed','disconnected'].includes(s.connectionState)||['failed','closed'].includes(s.iceConnectionState))return '연결 실패 · 다시 연결';return 'Connecting…';}
function networkPanel(){if(!test||!room)return '';const ids=[...new Set([...(room.members||[]).filter(p=>p.id!==room.id).map(p=>p.id),...room.peers.keys()])];const rows=ids.map(id=>{const member=room.members?.find(p=>p.id===id),s=room.peerState(id);return `<div><b>Peer: ${esc(id.slice(0,8))}</b> · ${esc(peerStatus(id))}<br><small>room member: ${member?'yes':'no'} · accepted: ${member?.accepted?'yes':'no'} · peer created: ${s.peerCreated?'yes':'no'} · offer sent: ${s.offerSent?'yes':'no'} · offer received: ${s.offerReceived?'yes':'no'} · answer sent: ${s.answerSent?'yes':'no'} · answer received: ${s.answerReceived?'yes':'no'}<br>signaling ${s.signalingState} · gathering ${s.iceGatheringState} · ICE ${s.iceConnectionState} · connection ${s.connectionState} · DataChannel ${s.dataChannel} · candidates local/remote ${s.localCandidates}/${s.remoteCandidates}<br>last error: ${esc(s.lastError||'none')}</small></div>`}).join('');return `<details class="mp-debug" open><summary>WebRTC debug</summary>${rows||'<p>Peer connection not created yet.</p>'}${networkDebug.slice(-5).map(e=>`<small>${new Date(e.at).toLocaleTimeString()} ${esc(e.id||'room')} ${esc(e.event)}</small>`).join('<br>')}</details>`;}
function pruneLobby(){if(!room?.isHost)return false;const live=new Set((room.members||[]).filter(p=>p.accepted).map(p=>p.id));live.add(room.id);let changed=false;for(const id of Object.keys(lobby))if(!live.has(id)){delete lobby[id];changed=true;}return changed;}
function gone(msg){sessionStorage.removeItem(sessionKey);room=null;lobby={};match=null;acks=[];pauseSince=0;error=msg||'방이 만료되었거나 방장이 나갔어요. 새 방을 만들어 주세요.';render(true);}
function statusTick(){if(!room)return;if(room.status==='gone'||room.closed){gone();return;}const now=Date.now();try{room.isHost?room.broadcast(envelope('ping')):room.send(room.host,envelope('ping'));}catch{}
  if(!room.isHost&&!match&&connected().length&&now-lastHello>3500&&selection.length===3){lastHello=now;try{room.send(room.host,envelope('hello',{test,player:publicPlayer(profile(),selection,side)}));}catch{}}
  if(room.isHost){if(pruneLobby()&&!match)publish();}
  if(room.isHost&&match&&match.phase!=='end'&&now>resumeGrace){
   const missing=Object.keys(lobby).filter(id=>id!==room.id&&(!connected().includes(id)||now-(lastSeen[id]||0)>8000));
   if(missing.length&&!pauseSince){pauseSince=now;match={...match,paused:true,version:match.version+1};publish();}
   else if(!missing.length&&pauseSince){pauseSince=0;match={...match,paused:false,version:match.version+1};publish();}
   else if(pauseSince&&now-pauseSince>60000){match={...match,phase:'end',winner:'abandoned',endedAt:now,version:match.version+1};publish();}
  }
  if(room.isHost&&match)publish();else if(match?.phase==='end')takeReward();render();
}
async function connect(code,resume){if(selection.length!==3)throw Error('먼저 서로 다른 포켓몬 카드 3장을 선택하세요.');room=new PeerRoom({onchange:()=>render(),onmessage:receive,onstatus:e=>{networkDebug=[...networkDebug.slice(-19),e];render(true);},onerror:e=>{if(/not found|expired|permission/i.test(e))gone(e);else{error=e;render();}}});if(resume)await room.resume(resume);else await room.open(code);
 if(test)window.__pocketTogetherDebug=()=>({members:room.members,lobby,connected:room.connected(),peers:[...room.peers.keys()].map(id=>({id,...room.peerState(id)})),events:room.debug});
 if(room.isHost&&!resume)lobby[room.id]={player:publicPlayer(profile(),selection,side),ready:false};keep();render(true);
}
function sendPlayer(){if(!room||match)return;if(room.isHost){if(lobby[room.id])lobby[room.id].ready=false;publish();}else if(connected().length)room.send(room.host,envelope('ready',{ready:false}));if(selection.length!==3)return;const player=publicPlayer(profile(),selection,side);if(room.isHost){lobby[room.id]={player,ready:false};publish();}else if(connected().length)room.send(room.host,envelope('hello',{test,player}));}
function cardArt(c){return `<img src="${esc(c.art)}" alt="${esc(c.name)}">`;}
function look(){return equippedLook(profile());}
function party(p){const me=p.id===profile().multiplayer.id;const bond=match.bondLevel>=2&&['raid','dungeon','tag'].includes(match.mode)?' · Bond Lv '+match.bondLevel:'';return `<div class="player-tile side-${p.side||0} ${match.actor===p.id?'turn':''} ${p.down?'down':''} ${me?look():''}"><b>${esc(p.name)}${me&&equippedTitle(profile())?' · '+esc(equippedTitle(profile())):''}${match.mode==='duel'||match.mode==='duo'?' · '+(p.side?'Orange':'Blue'):''}${bond}</b><div class="party-hp">${p.team.map(c=>`<span><em>${esc(byId(c.id).name)}</em><i><b style="width:${100*c.hp/c.max}%"></b></i><small>${c.hp}/${c.max}</small></span>`).join('')}</div></div>`;}
function foeBox(foe,label){const c=byId(foe.id),hp=foe.hp,max=foe.max||c.hp;return `<div class="enemy-zone"><div class="hp-label">${esc(label||c.name)} <span>${hp}/${max} HP</span></div><div class="hp-track"><i style="width:${100*hp/max}%"></i></div><div class="enemy-mon">${cardArt(c)}</div></div>`;}
function arena(){if(!match)return '';
 const me=mine()||match.players[0],a=byId(me.team[me.active].id),self=`<div class="player-zone"><div class="player-mon">${cardArt(a)}</div><div class="hp-label">${esc(a.name)} <span>${me.team[me.active].hp}/${a.hp} HP</span></div><div class="hp-track"><i style="width:${100*me.team[me.active].hp/a.hp}%"></i></div></div>`;
 if(match.mode==='raid'){const e=match.event,boss=byId(match.boss.id),hp=e?.after??match.boss.hp;return `<div class="arena mp-arena raid bond-lv-${match.bondLevel||1} ${look()}">${foeBox({id:boss.id,hp,max:match.boss.max},boss.name+' ★'+match.star)}${match.boss.shield>0?`<div class="shield-track"><i style="width:${100*match.boss.shield/match.boss.shieldMax}%"></i></div>`:''}${self}<div class="gauge team-gauge">${[0,1,2].map(i=>`<i class="${match.gauge>i?'on':''}"></i>`).join('')}<span>Team Attack ${match.gauge}/3</span></div></div>`;}
 if(match.mode==='dungeon'){if(!match.foe)return `<div class="arena mp-arena raid dungeon-rest ${look()}">${self}<span class="arena-label">${match.phase==='vote'?'TREASURE VOTE':match.phase==='quiz'?'QUIZ GATE':String(match.phase).toUpperCase()}</span></div>`;const e=match.event,hp=e?.after??match.foe.hp;return `<div class="arena mp-arena raid ${look()}">${foeBox({id:match.foe.id,hp,max:match.foe.max})}${self}<div class="gauge team-gauge">${[0,1,2].map(i=>`<i class="${match.gauge>i?'on':''}"></i>`).join('')}<span>Team Attack ${match.gauge}/3</span></div></div>`;}
 if(match.mode==='tag'){const e=match.event,foe=match.foes.find(f=>e&&String(f.id)===String(e.foe))||match.foes.find(f=>f.hp>0)||match.foes[0];return `<div class="arena mp-arena raid ${look()}">${foeBox(foe,'AI · '+byId(foe.id).name)}${self}<div class="gauge">${[0,1,2].map(i=>`<i class="${match.chain>i?'on':''}"></i>`).join('')}<span>Tag Chain ${match.chain}/3</span></div></div>`;}
 const e=match.event,actor=e?match.players.find(p=>p.id===e.actor):match.players.find(p=>p.id===match.actor),target=e?match.players.find(p=>p.id===e.target):match.players.find(p=>p.side!==actor.side&&alive(p))||match.players.find(p=>p.side!==actor.side);const b=byId(e?.foe||target.team[target.active].id),bhp=e?.after??target.team[target.active].hp,bmax=e?.max??b.hp;
 return `<div class="arena mp-arena ${look()}">${foeBox({id:b.id,hp:bhp,max:bmax})}${self}</div>`;
}
function qToken(){const id=profile().multiplayer.id;return match.mode==='raid'?raidQuestionToken(match,id):match.mode==='dungeon'?dungeonToken(match,id):match.mode==='tag'?tagToken(match,id):questionToken(match);}
function promptBox(p){const q=battlePrompt(p.learningLevel,{...p,battle:{turn:match.round??match.turn??0},battles:0});return `<h2>${esc(q.word)}</h2><p>Year ${p.learningLevel} · 알맞은 뜻을 고르세요.</p><div class="answers">${q.order.map(i=>btn(esc(q.options[i]),'answer:'+i,busy||pending||match.paused?'disabled':'')).join('')}</div>`;}
function coopMoves(me,disabled,extra){return `<h2>Choose a move · ⚡ ${me.energy}/3</h2>${extra||''}${btn('Basic · ⚡1','attack:basic',me.energy<1||disabled?'disabled':'')}${btn('Special · ⚡3','attack:special',me.energy<3||disabled?'disabled':'')}${btn('Guard','move:guard',disabled?'disabled':'')}${btn('Charge','move:charge',disabled?'disabled':'')}<div>${me.team.map((c,i)=>btn('교체 · '+esc(byId(c.id).name),'switch:'+i,!c.hp||i===me.active||disabled?'disabled':'')).join('')}</div>`;}
function combat(){const me=mine(),p=profile(),disabled=busy||pending||match.paused;let controls='';
 const endCopy=match.winner==='abandoned'?'연결이 복구되지 않아 종료했어요. 카드와 진도는 그대로예요.':match.mode==='raid'?(match.winner==='raiders'?'레이드 성공! 함께 해냈어요!':'아쉽게 막혔어요. 카드는 그대로예요.'):match.mode==='dungeon'?(match.winner==='clear'?'던전 클리어! 함께 걸어왔어요!':'여기서 멈췄어요. 카드는 그대로예요.'):match.mode==='tag'?(match.winner==='humans'?'Tag 승리! Duo 호흡이 맞았어요!':'좋은 대결이었어요!'):(match.winner==='draw'?'함께 끝까지 플레이했어요!':match.winner===me?.side?'우리 팀 승리!':'좋은 대결이었어요!');
 if(match.phase==='end')controls=`<h2>${endCopy}</h2><p>Adventure Medals · ${p.multiplayer.medals} 🏅 · Pack Shards ${p.multiplayer.shards} 🧩</p><p>보상 저장 확인 ${acks.length}/${match.players.length}</p>${btn('로비로','leave')}`;
 else if(match.paused)controls='<h2>Reconnecting…</h2><p>최대 60초 동안 기다립니다. 새로고침 후 이 방으로 복귀할 수 있어요.</p>';
 else if(busy)controls='<p>공격 연출 중…</p>';
 else if(match.mode==='dungeon'&&match.phase==='vote'){const n=match.nodes[match.node];controls=match.votes?.[me.id]?`<h2>친구의 선택을 기다려요</h2>`:`<h2>보물 투표</h2><p>둘 다 같은 것을 고르면 그대로, 다르면 첫 선택이 공유돼요. 한 아이만 갖지 않아요.</p>${n.options.map(i=>btn(esc(DUNGEON_ITEM_LABEL[i]||i),'vote:'+i)).join('')}`;}
 else if(match.mode==='dungeon'&&match.phase==='quiz')controls=match.answers?.[me.id]!==undefined?'<h2>친구의 답을 기다려요</h2>':`<h2>Quiz Gate</h2>${promptBox(p)}`;
 else if(['raid','dungeon','tag'].includes(match.mode)){
  const answered=match.answers?.[me?.id]!==undefined,moved=!!match.moves?.[me?.id];
  if(match.phase==='question'&&!answered)controls=`<h2>${me?.down?'Cheer · 구조 질문':match.mode==='tag'?'함께 답하면 Tag Chain':'함께 답해요'}</h2>${promptBox(p)}`;
  else if(match.phase==='question')controls='<h2>친구의 답을 기다려요</h2>';
  else if(me?.down)controls='<h2>다음 라운드를 기다려요</h2>';
  else if(moved)controls='<h2>친구의 행동을 기다려요</h2>';
  else if(match.mode==='tag'){const foes=match.foes.filter(f=>f.hp>0);controls=`<h2>Choose a move · ⚡ ${me.energy}/3 · Chain ${match.chain}/3</h2>${foes.map(f=>`<div><b>AI ${esc(byId(f.id).name)}</b>${btn('Basic · ⚡1','attack:basic:'+f.id,me.energy<1||disabled?'disabled':'')}${btn('Special · ⚡3','attack:special:'+f.id,me.energy<3||disabled?'disabled':'')}</div>`).join('')}${btn('Duo Move','move:duo',match.chain<3||disabled?'disabled':'')}${btn('Guard','move:guard',disabled?'disabled':'')}${btn('Charge','move:charge',disabled?'disabled':'')}`;}
  else controls=coopMoves(me,disabled,btn(match.mode==='dungeon'?'Team Attack':'Team Attack','move:team',(match.gauge||0)<3||disabled?'disabled':''));
 }else{
  const active=match.players.find(p=>p.id===match.actor),myTurn=active.id===me?.id;
  if(!myTurn)controls=`<h2>${esc(active.name)}의 차례</h2><p>속도 경쟁 없이 한 사람씩 진행해요.</p>`;
  else if(match.phase==='question')controls=promptBox(p);
  else{const targets=match.players.filter(x=>x.side!==me.side&&alive(x));controls=`<h2>Choose a move · ⚡ ${me.energy}/3</h2>${targets.map(t=>`<div><b>${esc(t.name)}</b>${btn('Basic · ⚡1','attack:basic:'+t.id,me.energy<1||disabled?'disabled':'')}${btn('Special · ⚡3','attack:special:'+t.id,me.energy<3||disabled?'disabled':'')}</div>`).join('')}${btn('Guard · 다음 공격 방어','move:guard',disabled?'disabled':'')}${btn('Charge · 에너지 모으고 턴 넘기기','move:charge',disabled?'disabled':'')}<div>${me.team.map((c,i)=>btn('교체 · '+esc(byId(c.id).name),'switch:'+i,!c.hp||i===me.active||disabled?'disabled':'')).join('')}</div>`;}
 }
 const title=match.mode==='raid'?`Raid ★${match.star} ${esc(RAID_LADDERS[match.ladder].name)} · Round ${match.round+1}`:match.mode==='dungeon'?`Dungeon · ${esc(DUNGEON_THEMES[match.theme].name)} · ${Math.min(5,match.node+1)}/5 · ${(match.nodes[match.node]||{type:match.winner||'end'}).type}`:match.mode==='tag'?`Duo Tag · 2 humans vs 2 AI · Round ${match.round+1}`:`Turn ${match.turn+1} · ${match.mode==='duo'?'2 vs 2 · 4 human players':'1 vs 1'}`;
 const map=match.mode==='dungeon'?`<ol class="dungeon-map">${match.nodes.map((n,i)=>`<li class="${i===match.node?'here':i<match.node?'done':''}">${n.type}</li>`).join('')}</ol><p class="muted">Run items: ${match.items.length?match.items.join(', '):'none'}</p>`:'';
 return `<section><p>${title}</p>${map}<div class="roster">${match.players.map(party).join('')}${match.mode==='tag'?match.foes.map(f=>`<div class="player-tile side-1"><b>AI · ${esc(byId(f.id).name)}</b><p>${f.hp}/${f.max} HP · ${f.role}</p></div>`).join(''):''}</div>${arena()}</section><section class="question">${controls}</section>`;
}
function starOpen(ladder,star){return star===1||(profile().multiplayer.raid?.stars?.[ladder]||0)>=star-1;}
function shopPanel(){const m=profile().multiplayer;const disc=DISCOVERY.filter(([,id])=>m.cosmetics.includes(id)).map(([n,id,name,kind])=>`<div class="shop-row"><b>${esc(name)}</b><span>Discovery ${n}</span>${btn(m.equipped[kind]===id?'착용 중':'착용','equip:'+id,m.equipped[kind]===id?'disabled':'')}</div>`).join('');return `<section class="mp-shop"><h2>Adventure Shop</h2><p>메달은 치장만 바꿉니다. 대전 숫자는 그대로예요.</p>${SHOP.map(item=>`<div class="shop-row"><b>${esc(item.name)}</b><span>${item.cost} 🏅</span>${m.cosmetics.includes(item.id)?btn(m.equipped[item.kind]===item.id?'착용 중':'착용','equip:'+item.id,m.equipped[item.kind]===item.id?'disabled':''):btn('구매','buy:'+item.id,m.medals<item.cost?'disabled':'')}</div>`).join('')}${disc}<p class="muted">Discovery ${DISCOVERY.map(([n,id,name])=>`${n} ${esc(name)}${m.cosmetics.includes(id)?' ✓':''}`).join(' · ')}</p></section>`;}
function rewardsPanel(){const m=profile().multiplayer;const bonds=Object.values(m.bond||{}).map(b=>`<div class="bond-row"><b>${esc(b.name||'Partner')}</b><span>Bond Lv ${b.level} · ${b.xp} XP</span><i><b style="width:${Math.min(100,b.level>=5?100:(b.xp%3)/3*100)}%"></b></i></div>`).join('');return `<section class="mp-rewards"><h2>Adventure Rewards</h2><p>${m.medals} 🏅 Medals · ${m.shards} / 5 🧩 Pack Shards · 승 ${m.wins} / 패 ${m.losses}</p>${bonds?`<div class="team-bonds"><h3>Team Bond</h3>${bonds}</div>`:''}${m.shards>=5?btn('조각 5개로 팩 1개 만들기','craft'):'<p class="muted">레이드·던전·태그 각각 하루 첫 성공마다 조각 1개. PVP는 0.</p>'}${Object.keys(m.raid?.stars||{}).length?`<p>레이드 별: ${Object.entries(m.raid.stars).map(([k,v])=>esc(RAID_LADDERS[k]?.name||k)+' ★'+v).join(' · ')}</p>`:''}${m.badges?.length?`<p>배지 ${m.badges.length} · 코스메틱 ${m.cosmetics.length}</p>`:''}</section>`+shopPanel();}
function modeHelp(){return {duel:'2명이면 1대1, 4명이면 실제 사람 2대2입니다.',raid:'실제 두 명이 한 보스를 함께 공략합니다. 2 humans vs 2 AI가 아닙니다.',dungeon:'두 명이 같은 지도를 걷습니다. 보물은 함께 고르고, 아이템은 이번 탐험에서만 씁니다.',tag:'두 명이 2 AI와 태그합니다. 4인 사람 대전은 Duel 2v2를 쓰세요.'}[playMode];}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&room)room.tick().catch(e=>{error=e.message;render(true);});});
function render(force=false){if(busy&&!force)return;const signature=JSON.stringify([profileId,room?.code,room?.members,connected(),lobby,match,acks,selection,side,error,pending,busy,filter,playMode,raidLadder,raidStar,dungeonTheme]);if(!force&&signature===lastSignature)return;lastSignature=signature;
 const p=profile();if(p)root.className='together '+look();
 const heading=`<header><h1>Together <small>대전 테스트본</small></h1>${room?(room.isHost?btn('참가자 새로고침','refresh'):'')+btn('방 나가기','leave'):`<a href="./${test?'?test=1':''}">게임으로 돌아가기</a>`}</header><p class="status" role="status">${error?'<span class="error">'+esc(error)+'</span>':room?'연결 '+connected().length+' · '+(test?'부모 테스트 전용':'일반 기록'):'카드를 잃지 않는 친구 대결 · 최대 4명 · 협동 2인'}</p>${networkPanel()}`;
 if(!p){root.innerHTML=heading+'<section>먼저 게임에서 프로필을 만들어 주세요.</section>';return;}
 if(match){root.innerHTML=heading+combat();return;}
 const owned=[...new Set(p.cards.map(String))].map(byId).filter(c=>c?.battleEligible!==false&&c);const available=owned.filter(c=>c.name.toLowerCase().includes(filter.toLowerCase()));
 const hostLock=room&&!room.isHost,need=TWO.includes(playMode)?2:null;
 root.innerHTML=heading+`<section class="mp-modes"><p>모드 ${[['duel','Trainer Duel'],['raid','Boss Raid · 2인'],['dungeon','Dungeon · 2인'],['tag','Tag vs 2 AI']].map(([id,label])=>btn(label,'mode:'+id,`aria-pressed="${playMode===id}" ${hostLock?'disabled':''}`)).join('')}</p><p class="muted">${modeHelp()}</p>${playMode==='raid'?`<div class="raid-pick">${Object.entries(RAID_LADDERS).map(([id,l])=>btn(l.name,'ladder:'+id,`aria-pressed="${raidLadder===id}" ${hostLock?'disabled':''}`)).join('')}</div><div class="raid-pick">${RAID_STARS.map(n=>btn('★'.repeat(n),'star:'+n,`aria-pressed="${raidStar===n}" ${hostLock||!starOpen(raidLadder,n)?'disabled':''}`)).join('')}</div>`:''}${playMode==='dungeon'?`<div class="raid-pick">${Object.entries(DUNGEON_THEMES).map(([id,t])=>btn(t.name,'theme:'+id,`aria-pressed="${dungeonTheme===id}" ${hostLock?'disabled':''}`)).join('')}</div>`:''}</section>`+rewardsPanel()+`<section><label>Trainer <select id="mp-profile" ${room?'disabled':''}>${Object.entries(saved.profiles).map(([id,p])=>`<option value="${id}" ${id===profileId?'selected':''}>${esc(p.displayName)} · Year ${p.learningLevel}</option>`).join('')}</select></label><p>${p.multiplayer.medals} 🏅 · 세 장을 골라 주세요 (${selection.length}/3).</p>${playMode==='duel'?`<p>팀 ${btn('Blue','side:0',`aria-pressed="${side===0}"`)}${btn('Orange','side:1',`aria-pressed="${side===1}"`)}</p>`:''}<label>카드 찾기 <input id="mp-filter" class="mp-card-filter" value="${esc(filter)}" placeholder="Pokémon name" autocomplete="off"></label><div class="mp-cards">${available.map(c=>btn(cardArt(c)+esc(c.name),'card:'+c.id,`aria-pressed="${selection.some(id=>String(id)===String(c.id))}"`)).join('')}</div>${owned.length<3?'<p>학습으로 팩을 얻어 포켓몬 3종을 모으면 참가할 수 있어요. 부모 테스트에서는 바로 체험할 수 있어요.</p>':''}</section>`;
 if(!room)root.innerHTML+=`<section><h2>친구와 만나기</h2>${btn('Create room · 방 만들기','create')}<label>Room code <input id="mp-code" maxlength="6" autocomplete="off" placeholder="ABC123"></label>${btn('Join room · 참가','join')}<p class="mp-help">같은 테스트 서버에 접속한 기기끼리 연결합니다. 방장은 참가 요청을 승인해 주세요. 공식 사이트는 변경하지 않는 미리보기입니다.</p></section>`;
 else{const entries=Object.entries(lobby),members=(room.members||[]).filter(p=>p.id!==room.id&&p.accepted),pending=members.filter(p=>!lobby[p.id]).map(p=>`<div class="player-tile"><b>참가자 ${esc(p.id.slice(0,6))}</b><p>${peerStatus(p.id)}</p></div>`).join(''),shown=Math.max(entries.length+pending.length,1);root.innerHTML+=`<section><h2>방 코드 <span class="room-code">${room.code}</span></h2><p>${shown}${need?'/'+need:''} 참가${playMode==='duel'?` · Blue ${entries.filter(([,v])=>v.player.side===0).length} / Orange ${entries.filter(([,v])=>v.player.side===1).length} · 2명 1v1 · 4명 사람 2v2`:' · 2인 협동'}</p><div class="roster">${entries.map(([id,v])=>`<div class="player-tile side-${v.player.side}"><b>${esc(v.player.name)}</b><p>Year ${v.player.year} · ${v.ready?'Ready ✓':peerStatus(id)}</p></div>`).join('')}${pending}</div>${room.isHost?btn('참가자 새로고침','refresh'):''}${btn(lobby[room.id]?.ready?'준비 취소':'Ready · 준비 완료','ready',selection.length!==3?'disabled':'')}${room.isHost?btn(playMode==='raid'?'Start raid':playMode==='dungeon'?'Start dungeon':playMode==='tag'?'Start tag':'Start battle · 대결 시작','start'):''}<p>${TWO.includes(playMode)?'두 명이 Ready면 시작합니다.':'1v1은 2명, 2v2는 실제 사람 4명. 태그로 대체하지 않아요.'}</p></section>`;}
}
function restoreFilterFocus(pos){const input=document.querySelector('#mp-filter');if(input){input.focus();if(typeof pos==='number')input.setSelectionRange(pos,pos);}}
root.addEventListener('input',e=>{if(e.target.id!=='mp-filter')return;filter=e.target.value;const pos=e.target.selectionStart;render(true);restoreFilterFocus(pos);});
root.addEventListener('change',e=>{try{if(e.target.id==='mp-profile'){selectProfile(e.target.value);filter='';render(true);}}catch(e){error=e.message;render();}});
root.addEventListener('click',async e=>{const el=e.target.closest('[data-mp]');if(!el||el.disabled)return;const [action,v,w]=el.dataset.mp.split(':');try{error='';
 if(action==='create')await connect();
 if(action==='join'){const code=document.querySelector('#mp-code')?.value.trim()||'';if(!/^[A-Za-z0-9]{6}$/.test(code))throw Error('방 코드 6자리를 확인해 주세요.');await connect(code);}
 if(action==='accept')await room.accept(v);
 if(action==='refresh'){await room.tick();render(true);}
 if(action==='card'){const c=byId(v),i=selection.findIndex(x=>String(x)===String(c.id));if(i>=0)selection.splice(i,1);else if(selection.length<3)selection.push(c.id);sendPlayer();}
 if(action==='side'){side=Number(v);sendPlayer();}
 if(action==='mode'){if(room&&!room.isHost)return;playMode=v;if(room?.isHost)publish();else render(true);}
 if(action==='ladder'){if(room&&!room.isHost)return;raidLadder=v;if(!starOpen(raidLadder,raidStar))raidStar=1;if(room?.isHost)publish();else render(true);}
 if(action==='star'){if(room&&!room.isHost)return;const n=Number(v);if(!starOpen(raidLadder,n))throw Error('이전 별을 먼저 클리어해 주세요.');raidStar=n;if(room?.isHost)publish();else render(true);}
 if(action==='theme'){if(room&&!room.isHost)return;dungeonTheme=v;if(room?.isHost)publish();else render(true);}
 if(action==='ready'){if(selection.length!==3)throw Error('카드 3장을 골라 주세요.');if(!room.isHost&&!connected().length)throw Error('연결이 끝날 때까지 기다려 주세요. 방장이 참가를 승인해야 해요.');const ready=!lobby[room.id]?.ready;sendPlayer();if(room.isHost){lobby[room.id].ready=ready;publish();}else room.send(room.host,envelope('ready',{ready}));}
 if(action==='start'){if(!room.isHost)return;const entries=Object.entries(lobby);if(!entries.every(([id,p])=>p.ready&&(id===room.id||connected().includes(id))))throw Error('모든 참가자의 연결과 Ready를 확인해 주세요.');const people=entries.map(([,p])=>p.player);if(TWO.includes(playMode)&&people.length!==2)throw Error('이 모드는 실제 사람 두 명이 필요해요.');if(playMode==='duel'&&![2,4].includes(people.length))throw Error('1대1은 2명, 2대2는 실제 사람 4명이 필요해요.');const pair=people.length===2?[people[0].id,people[1].id].sort().join(':'):'';const bondLevel=profile().multiplayer.bond?.[pair]?.level||1;match=playMode==='raid'?createRaid(people,room.code,{ladder:raidLadder,star:raidStar,bondLevel}):playMode==='dungeon'?createDungeon(people,room.code,{theme:dungeonTheme}):playMode==='tag'?createTag(people,room.code):createMatch(people,room.code);await room.request('/'+room.code+'/start',{});publish();}
 if(action==='answer')act({type:'question_result',questionToken:qToken(),correct:Number(v)===0});
 if(action==='vote')act({type:'vote',item:v});
 if(action==='attack')act({type:'battle_action',move:v,target:w});
 if(action==='move')act({type:'battle_action',move:v});
 if(action==='switch')act({type:'battle_action',move:'switch',index:Number(v)});
 if(action==='craft'){const next=craftPack(profile());if(!next)throw Error('조각 5개가 필요해요.');writeProfile(next);}
 if(action==='buy'){const next=buyCosmetic(profile(),v);if(!next)throw Error('메달이 부족하거나 이미 가지고 있어요.');writeProfile(next);}
 if(action==='equip'){const next=equipCosmetic(profile(),v);if(!next)throw Error('아직 없는 장식이에요.');writeProfile(next);}
 if(action==='leave'){animation?.cancel();if(room)await room.close().catch(()=>{});sessionStorage.removeItem(sessionKey);room=null;lobby={};match=null;acks=[];pauseSince=0;pending=false;busy=false;render(true);return;}
 keep();render();}catch(e){if(room&&!room.code){room.closed=true;room=null;}error=e.message;render(true);}});
try{saved=read();const previous=JSON.parse(sessionStorage.getItem(sessionKey)||'null');profileId=previous?.profileId||saved.active||saved.profileOrder[0];if(profileId)selectProfile(profileId);if(previous&&Date.now()-previous.at<7200000){({lobby,match,acks,selection,side,pauseSince,playMode='duel',raidLadder='electric',raidStar=1,dungeonTheme='forest'}=previous);resumeGrace=Date.now()+12000;for(const id of Object.keys(lobby||{}))lastSeen[id]=Date.now();try{await connect(null,previous.credentials);if(room.isHost)publish();}catch{sessionStorage.removeItem(sessionKey);room=null;lobby={};match=null;error='이전 방을 찾지 못했어요. 새 방을 만들어 주세요.';}}render(true);setInterval(statusTick,2000);}catch(e){error=e.message;root.innerHTML=`<h1>Together</h1><p class="error">${esc(error)}</p><a href="./${test?'?test=1':''}">게임으로 돌아가기</a>`;}
