// Transcript matching is a sentence check, never an acoustic/phoneme score.
export function normaliseSpeech(value){return String(value).normalize('NFKC').toLowerCase().replace(/[’‘]/g,"'").replace(/\b(can't)\b/g,'cannot').replace(/\b(won't)\b/g,'will not').replace(/\b(i'm)\b/g,'i am').replace(/\b(it's)\b/g,'it is').replace(/\b(let's)\b/g,'let us').replace(/\b([a-z]+)'ll\b/g,'$1 will').replace(/\b([a-z]+)'re\b/g,'$1 are').replace(/\b([a-z]+)n't\b/g,'$1 not').replace(/\bcolor(s)?\b/g,'colour$1').replace(/\borganize\b/g,'organise').replace(/\bpractice\b/g,'practise').replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim();}
const SPEECH_STOP_WORDS=new Set('a an and are at can for i in is it let me my of on our please should the to us we will with your'.split(' '));
function contentWords(value){return value.split(' ').filter(word=>word&&!SPEECH_STOP_WORDS.has(word));}
function orderedSimilarity(target,heard){const a=target.split(' ').filter(Boolean),b=heard.split(' ').filter(Boolean);if(!a.length||!b.length)return 0;const row=Array(b.length+1).fill(0);for(const word of a){let diagonal=0;for(let i=1;i<=b.length;i++){const previous=row[i];row[i]=word===b[i-1]?diagonal+1:Math.max(row[i],row[i-1]);diagonal=previous;}}const common=row[b.length];return Math.min(common/a.length,common/b.length);}
export function checkSpokenSentence(expected,transcripts){const target=normaliseSpeech(expected),targetContent=contentWords(target);const options=transcripts.map(t=>{const normal=normaliseSpeech(t),content=contentWords(normal);return {text:t,normal,similarity:orderedSimilarity(target,normal),contentSimilarity:targetContent.length?orderedSimilarity(targetContent.join(' '),content.join(' ')):1};});const best=options.sort((a,b)=>b.similarity-a.similarity)[0]||{text:'',similarity:0,contentSimilarity:0};return {matched:best.normal===target||(best.similarity>=.7&&best.contentSimilarity>=.7),heard:best.text,similarity:best.similarity};}
// Injectable recognition constructor keeps lifecycle checks independent of a real microphone.
export function startSentenceRecognition({Recognition,expected,onStatus,onMatch,onEnd}){const r=new Recognition();let active=true,accepted=false,timer;
 r.lang='en-NZ';r.continuous=false;r.interimResults=false;r.maxAlternatives=3;
 const stop=()=>{if(!active)return;active=false;clearTimeout(timer);r.onresult=null;r.onerror=null;r.onend=null;try{r.abort();}catch{}};
 r.onresult=e=>{if(!active||accepted)return;const result=e.results[e.resultIndex??0];if(!result?.isFinal)return;const checked=checkSpokenSentence(expected,Array.from(result,x=>x.transcript));if(checked.matched){accepted=true;stop();onMatch(checked.heard);}else onStatus('mismatch',checked.heard);};
 r.onerror=e=>{if(!active)return;onStatus(e.error||'error','');stop();onEnd();};r.onend=()=>{if(!active)return;active=false;clearTimeout(timer);onEnd();};
 try{r.start();if(active)timer=setTimeout(()=>{stop();onStatus('timeout','');onEnd();},9000);}catch{stop();onStatus('unavailable','');onEnd();}
 return {stop};}
