// Original bridge lessons. Core words are assessed; exposure words are supported in context only.
export const YEAR4=[];
function add(w,s,story,r,l,exposure){YEAR4.push({year:4,words:w.split(';').map(x=>x.split('|')),s,story,r,l,exposure,focus:YEAR4.length<8?'Explain everyday choices with because and so.':YEAR4.length<16?'Connect ideas and find clues in a short text.':'Compare ideas, give a reason and plan a next step.'});}
add('prepare|준비하다|get ready for something;follow|따르다|do what instructions say;understand|이해하다|know what something means;finish|끝내다|do the last part',
 ['I prepare my bag before school.','We follow the steps to finish our work.'],
 'Tony and Kai prepare their bags for school. Their teacher gives the class three steps for making a poster. Tony does not understand the second step, so he asks her to show an example. Now he can follow the steps. He checks each one before he says the work is finished. The example helped him work independently.',
 [['What helps Tony understand the second step?','An example from the teacher','A new school bag','A longer lunch break'],['Why does Tony check the steps?','To make sure he has finished the whole task','To change every instruction','To avoid making a poster']],
 ['The speaker gets a bag ready before school.','The speaker buys a new bag after school.','The speaker leaves a bag at school.'],[['independently','스스로','without someone doing it for you']]);
add('greet|인사하다|say hello to someone;share|나누다|let others use or have some;friendly|다정한|kind and welcoming;support|도와주다|help someone when they need it',
 ['We greet our new classmate with a smile.','I can share my ideas and support others.'],
 'A new classmate arrives during morning tea. Kai and Tony greet her with a smile. She wants to build with the blocks, but she is unsure where to start. They share the blocks and ask about her ideas. Their friendly welcome helps her join in. When her tower falls, they support her by helping her try again.',
 [['What do the children share?','Blocks','Their lunches','Bus tickets'],['Which action shows support?','Helping her try again after the tower falls','Building without listening to her','Putting all the blocks away']],
 ['The children say hello in a welcoming way.','The children say goodbye for the holidays.','The children ask for a quiet room.'],[['welcome','환영','a kind greeting for someone arriving']]);
add('healthy|건강에 좋은|good for your body;snack|간식|a small amount of food between meals;refill|다시 채우다|fill something again;prefer|더 좋아하다|like one thing more than another',
 ['I prefer a healthy snack after swimming.','Please refill your bottle before we leave.'],
 'After swimming, Tony feels hungry and thirsty. He would prefer an apple for his snack today, but he only has a sandwich. His dad explains that different foods help our bodies in different ways. Tony eats the sandwich and saves room for fruit at home. Before they leave, he remembers to refill his water bottle at the fountain.',
 [['What does Tony eat after swimming?','A sandwich','An apple','An ice cream'],['Why does he refill the bottle?','So he has water for the journey home','So he can carry less water','So he can replace his snack']],
 ['The speaker likes a healthy snack after swimming.','The speaker wants to swim after every meal.','The speaker does not want any food.'],[['fountain','음수대','a place where drinking water comes out']]);
add('cloudy|구름이 낀|with many clouds in the sky;shower|소나기|rain that lasts a short time;temperature|기온|how hot or cold something is;protect|보호하다|keep something safe from harm',
 ['A cloudy sky may bring a shower.','My jacket helps protect me from the rain.'],
 'The class plans a walk to the park. It is cloudy, and the weather report says a shower may arrive after lunch. The temperature is lower than yesterday. Tony packs a jacket to protect himself from the rain and cold. The walk still goes ahead. A short shower arrives, but the children stay comfortable because they brought the right clothes.',
 [['What does Tony pack?','A jacket','A sun umbrella','A picnic blanket'],['Why can the children enjoy the walk?','They prepared for the weather','They knew it could never rain','They stayed inside all day']],
 ['The speaker thinks a short period of rain is possible.','The speaker promises snow all day.','The speaker says the sky has no clouds.'],[['comfortable','편안한','feeling warm and well enough']]);
add('direction|방향|the way something goes;nearby|가까이에|not far away;across|건너서|from one side to the other;map|지도|a drawing that shows places',
 ['The map shows a library nearby.','We walk across the road at the crossing.'],
 'Tony wants to find the library after school. He checks a map with his whānau. The library is nearby, but a busy road is between them and the entrance. The map shows a crossing further along the road. They walk in that direction and go across safely. The shortest line on a map is not always the best walking route.',
 [['Where do they cross the road?','At the crossing','Between parked cars','Outside the library entrance'],['Why do they walk further along the road?','To use a safer crossing','To get further away from the library','To avoid using the map']],
 ['A library is shown not far away.','The library is missing from every map.','The speaker is inside a faraway library.'],[['route','이동 경로','the way you take to a place']]);
add('cost|가격이 들다|have a price;total|합계|the whole amount added together;cheaper|더 싼|costing less money;decide|결정하다|choose after thinking',
 ['These pencils cost less than those ones.','We decide after checking the total cost.'],
 'The class has ten dollars for art supplies. A large packet of pencils costs eight dollars. Two small packets cost six dollars in total and contain the same number of pencils. Tony checks the labels before helping the group decide. They choose the cheaper option and keep four dollars for paper. Comparing the packets helps them use their budget well.',
 [['How much do two small packets cost in total?','Six dollars','Eight dollars','Ten dollars'],['Why does the class choose the small packets?','They get the same number of pencils for less money','The packets have more colours','They want to spend all ten dollars']],
 ['One set of pencils is cheaper than the other.','Both sets of pencils are free.','The speaker has already bought both sets.'],[['budget','예산','the money available to spend']]);
add('patient|참을성 있는|able to wait without getting angry;equal|똑같은|the same in amount;solve|해결하다|find an answer to a problem;calmly|차분하게|without getting upset or shouting',
 ['We take equal turns with the ball.','We can solve this problem by talking calmly.'],
 'Two groups want to use the same ball at morning tea. One group has waited longer, but both want a whole game. Tony listens patiently as they explain. He suggests equal turns of five minutes. The children talk calmly and agree to try it. A timer helps them follow the plan. They solve the problem without stopping either group from playing.',
 [['How long is each turn?','Five minutes','Ten minutes','The whole morning'],['What makes the plan fair?','Both groups get the same time with the ball','Only the first group plays','The loudest group keeps the ball']],
 ['Each person gets the same amount of time with the ball.','One person keeps the ball all day.','The speaker wants to stop the game.'],[['patiently','참을성 있게','in a patient way']]);
add('clean|깨끗이 하다|remove dirt;mend|수선하다|fix something that is torn or broken;store|보관하다|keep something in a place until needed;waste|낭비하다|use more than is needed or throw useful things away',
 ['We clean our tools before storing them.','I can mend this bag instead of buying another.'],
 'After gardening, Tony notices a small hole in his cloth bag. He could throw it away, but most of the bag is still strong. His aunt helps him mend the hole with a patch. They clean the garden tools and store them in a dry cupboard. Looking after useful things means the family does not waste them or need replacements so often.',
 [['How do they mend the bag?','With a patch','With water','With a new cupboard'],['Why is mending a good choice here?','Most of the bag can still be used','The bag is too small for anything','A new bag would have no holes']],
 ['The tools are cleaned before being put away.','The tools are left outside in the rain.','The tools are bought after gardening.'],[['replacement','대체품','something used in place of another thing']]);
add('plot|줄거리|the main events of a story;detail|세부 내용|one small piece of information;theme|주제|an important idea in a story;describe|묘사하다|say what something is like',
 ['One small detail helps us understand the character.','I can describe how the story ends.'],
 'Tony reads a story about a child who loses a race but stays to cheer for a friend. He first describes the plot: the training, the race and the cheering at the end. Then he notices a detail. The child smiles when the friend wins. Tony thinks friendship is a theme because the child values a friend more than a prize. His partner finds another clue that supports this idea.',
 [['Which detail does Tony notice?','The child smiles when the friend wins','The child hides the prize','The friend misses the race'],['Why might friendship be a theme?','The child cares about a friend even after losing','Every story about racing has the same theme','The child trained every morning']],
 ['A small piece of information helps explain a character.','Every small detail must be left out.','The speaker has forgotten the character.'],[['character','등장인물','a person or creature in a story'],['clue','단서','something that helps you work out an answer']]);
add('root|뿌리|the part of a plant that takes in water from soil;stem|줄기|the part that holds up leaves;growth|성장|the process of getting bigger;sunlight|햇빛|light from the sun',
 ['The root takes water from the soil.','We measure growth and record how much sunlight reaches each plant.'],
 'The class grows two bean plants in matching pots. Each plant has a root in the soil and a stem holding its leaves. They give both plants the same amount of water, but one receives less sunlight. Each week they measure the growth. After three weeks, the plants look different. The children compare their records before discussing how light may have affected them. They know one experiment does not answer every question about plants.',
 [['What do the children keep the same?','The amount of water','The amount of sunlight','The height of the plants'],['Why do they use records?','To compare what happened over time','To make both plants identical','To stop the roots taking in water']],
 ['A plant gets water from the soil through its root.','A plant gets all its water from sunlight.','A stem keeps every root dry.'],[['measure','측정하다','find the size or amount'],['experiment','실험','a planned way to test an idea']]);
add('coast|해안|land beside the sea;wave|파도|moving water that rises and falls;rockpool|바위 웅덩이|seawater left between rocks as the tide goes out;pollution|오염|harmful things added to water air or land',
 ['A wave washes over the rocks nearby.','We leave each rockpool as we found it.'],
 'On a visit to the coast, Tony watches a wave break near a rockpool. His group stays with the adult leading the walk. They spot a small crab sheltering under a rock. Nearby, a plastic wrapper floats in shallow water. Their guide explains that rubbish can cause pollution and harm sea creatures. She safely collects it with a tool. The children look closely without moving the crab or taking anything home.',
 [['What does the guide collect?','A plastic wrapper','A crab','A large rock'],['Why do the children leave the crab there?','It belongs in its living place','It is made of plastic','It needs to travel home with them']],
 ['Moving seawater rises and breaks near some rocks.','All the water has disappeared from the coast.','The rocks are being carried to school.'],[['tide','밀물과 썰물','the regular rise and fall of the sea'],['sheltering','몸을 피하는','staying in a protected place']]);
add('journey|여정|a trip from one place to another;station|역|a place where trains stop;board|탑승하다|get onto a bus train or boat;cancel|취소하다|decide that something planned will not happen',
 ['We wait at the station with our tickets.','Our journey will change if they cancel this train.'],
 'Tony and his whānau reach the station for a journey into town. An announcement says their train is cancelled. They check the screen and ask a staff member about another service. A bus will take passengers to the next station. Before they board, they check that it goes in the right direction. They arrive later than planned, so they message the family member waiting for them. Checking information helps them make a new plan.',
 [['Why do they take a bus?','Their train is cancelled','They forgot where the station is','They want to leave their tickets behind'],['Why do they send a message?','Someone waiting needs to know they will be late','They want the train to disappear','They have already returned home']],
 ['The speakers wait with tickets at a train stop.','The speakers leave their tickets at home.','The speakers have finished every journey.'],[['announcement','안내 방송','information spoken for everyone to hear'],['passenger','승객','someone travelling in a vehicle']]);
add('nervous|긴장한|worried about something that may happen;relaxed|편안한|calm and not worried;upset|속상한|unhappy or worried;solution|해결책|a way to deal with a problem',
 ['I feel nervous before speaking to the class.','A quiet practice helps me feel more relaxed.'],
 'Tony feels nervous about reading his story aloud. He is upset when he loses his place during practice. His friend listens and asks which part feels hardest. Together they find a solution: mark the paragraphs and practise one at a time. Tony feels more relaxed after a few tries. He still feels a little nervous on the day, but he knows where to pause. Feeling nervous does not mean he cannot do it.',
 [['What helps Tony keep his place?','Marking the paragraphs','Reading every word faster','Putting his story away'],['What does the ending suggest?','He can try even while feeling a little nervous','He must never feel nervous again','His friend should always speak for him']],
 ['The speaker feels worried before addressing the class.','The speaker has no story to read.','The speaker feels sleepy after lunch.'],[['pause','잠깐 멈추다','stop for a short time'],['paragraph','문단','a group of sentences about one idea']]);
add('role|역할|a job someone has in a group;discuss|의논하다|talk about ideas together;cooperate|협력하다|work together to help each other;complete|완료하다|finish all parts of something',
 ['We discuss each role before starting our project.','We cooperate so everyone can complete a useful part.'],
 'Four children plan a class display about local birds. First they discuss what needs doing. One role is checking facts, another is drawing, and two involve writing and arranging the display. A child who finishes early offers help instead of taking over someone else’s work. They cooperate to complete the display before Friday. At the end, they explain how each person helped. Their different skills make the whole display clearer.',
 [['What is one role in the project?','Checking facts','Selling bird food','Choosing a new classroom'],['Why does the child offer help instead of taking over?','To support the group while respecting each role','To avoid finishing the display','To make only one person do everything']],
 ['The group talks about each job before starting.','The group finishes without planning any jobs.','The group asks one person to do every job.'],[['display','전시물','work arranged for people to look at'],['take over','대신 맡아 버리다','start doing a job someone else was doing']]);
add('recipe|요리법|instructions for making a dish;slice|얇게 썰다|cut into thin pieces;boil|끓이다|heat a liquid until it bubbles;taste|맛보다|try a little food to notice its flavour',
 ['We read the recipe before preparing our ingredients.','An adult will boil the water for our soup.'],
 'Tony and his uncle choose a vegetable soup recipe. They read all the instructions before starting. Tony washes the vegetables, and his uncle helps him slice them safely. His uncle puts the pot on the stove and waits for the water to boil. When the soup has cooled enough, they taste a small spoonful. It needs a little more flavour, so they add herbs. Reading ahead helped them know which jobs needed an adult.',
 [['Who heats the water on the stove?','Tony’s uncle','Tony alone','A classmate'],['Why did they read all the instructions first?','To plan the steps and identify jobs needing an adult','To avoid using any ingredients','To make the water cool faster']],
 ['The speakers check the cooking instructions before preparing food.','The speakers taste the food before it exists.','The speakers choose a recipe after eating.'],[['herb','허브','a plant used to add flavour'],['stove','레인지','equipment used for heating food']]);
add('culture|문화|shared ways of living and expressing ideas;ceremony|의식|a planned event marking something important;special|특별한|different from usual and important;community|공동체|people connected by a place or shared interests',
 ['Our community shares stories at a special gathering.','We ask before joining a ceremony we do not know.'],
 'The school community plans an evening where families may share stories, songs or food. Some families choose to watch, and others take part. Tony learns that culture can be expressed in many ways, even within one family. Before a special ceremony, a host explains what guests should do. Tony listens and asks politely when he is unsure. He notices that respectful questions help him learn without assuming that everyone has the same customs.',
 [['Who explains what guests should do?','A host','A visitor who is guessing','Every child at once'],['Why does Tony ask when unsure?','To learn how to show respect','To prove every family is the same','To change the ceremony immediately']],
 ['People connected to the speaker gather to share stories.','Everyone must share the same story.','The speaker is describing an empty school.'],[['custom','관습','a way of doing things in a group'],['host','주최자','someone welcoming guests']]);
add('password|비밀번호|a secret set of characters used to sign in;safe|안전한|protected from danger;trust|신뢰하다|believe someone or something can be relied on;report|알리다|tell an appropriate person about something',
 ['I keep my password private to stay safe online.','I report worrying messages to an adult I trust.'],
 'While playing an online game, Tony receives a message offering free items in exchange for his password. The sender uses a familiar-looking picture, but Tony does not know who is behind it. He wants to stay safe, so he does not reply or open the link. Instead, he shows the message to an adult he can trust. They report it using the game’s tools. Tony learns that a friendly picture is not proof that a request is safe.',
 [['What does Tony do with the message?','Shows it to a trusted adult','Sends his password','Opens the link for free items'],['Why is the picture not enough to trust the sender?','Someone can use a picture without being that person','Every picture online is dangerous','Only messages without pictures are safe']],
 ['The speaker protects a sign-in secret.','The speaker shares a password with every player.','The speaker forgets how to play offline.'],[['private','비공개의','kept for yourself or allowed people'],['proof','증거','information showing something is true']]);
add('environment|환경|the natural world around living things;forest|숲|a large area with many trees;creature|생물|a living animal;survive|살아남다|stay alive',
 ['Every creature needs a suitable place to live.','Protecting our forest environment helps native birds survive.'],
 'The class visits a forest with a local guide. She asks them to listen before they speak. They hear birds, insects and leaves moving in the wind. Each creature depends on parts of this environment to survive. A fallen log may look untidy, but it shelters insects and helps the soil as it breaks down. Tony changes his idea that a healthy forest must look neat. The class stays on the path and leaves the log where it is.',
 [['What can a fallen log provide?','Shelter for insects','A road for buses','A clean lunch table'],['Why does Tony change his idea?','He learns that something untidy can still help living things','He sees that every log must be removed','He hears no animals in the forest']],
 ['All animals need places that meet their needs.','Every animal can live in the same small box.','Only large animals need somewhere to live.'],[['native','토착의','naturally found in a place'],['depend on','의지하다','need something or someone']]);
add('compost|퇴비|decayed plant material used to help soil;plastic|플라스틱|a material used for many containers and objects;collect|모으다|bring things together;save|절약하다|keep something from being used unnecessarily',
 ['We collect suitable food scraps for the compost bin.','Reusing containers can save materials and reduce plastic waste.'],
 'The class checks what is being thrown away after lunch. They collect information for three days before suggesting changes. Many scraps can go into the school compost, but plastic wrappers cannot. Tony suggests clear signs with examples above each bin. Another group suggests reusable containers to save materials. The class tries both ideas for a week, then checks the bins again. They want to know whether their plan actually reduces waste, rather than only looking helpful on a poster.',
 [['What cannot go into the school compost here?','Plastic wrappers','Suitable food scraps','Decayed plant material'],['Why do they check the bins again?','To find out whether the changes helped','To count only the new signs','To make more plastic wrappers']],
 ['Appropriate food scraps are gathered for compost.','All plastic is put into compost.','The speakers stop using every school bin.'],[['reusable','재사용 가능한','able to be used again'],['reduce','줄이다','make something smaller in amount']]);
add('warm-up|준비 운동|gentle exercise before harder activity;skill|기술|an ability learned through practice;effort|노력|energy used to try hard;routine|정해진 순서|a usual set of actions',
 ['A gentle warm-up is part of our practice routine.','Regular effort helps me improve a skill over time.'],
 'Tony wants to improve his passing in netball. At practice, the coach begins with a warm-up and explains the routine. Tony tries to pass faster, but the ball often misses its target. The coach suggests slowing down and checking his hand position first. After several sessions, his passes become more accurate. He notices that useful effort means practising carefully, not only repeating quickly. His skill develops gradually, and he records one small improvement after each session.',
 [['What does the coach suggest first?','Slow down and check hand position','Pass as fast as possible','Stop warming up'],['What does Tony learn about effort?','Careful practice can help more than rushing','Repeating quickly always gives the best result','A skill should improve without practice']],
 ['Practice begins with gentle exercise as a usual step.','The speaker finishes all practice without moving.','The speaker only practises a skill once.'],[['accurate','정확한','close to the intended result'],['gradually','점차','little by little over time']]);
add('unusual|특이한|different from what is usual;possibility|가능성|something that might be true or happen;pattern|패턴|a repeated or regular way things happen;result|결과|what happens after an action or test',
 ['We notice an unusual pattern in our results.','One possibility is that the surface changed the distance.'],
 'Groups roll the same toy car down a ramp onto different surfaces. Most results form a pattern: the car travels further on smooth flooring. One unusual result shows a very short distance there. Tony suggests one possibility: the car may have touched the edge of the ramp. They check their notes and repeat that run carefully. The new result fits the pattern. They keep the original result in their record and explain why they checked it instead of quietly deleting it.',
 [['What do they do about the unusual result?','Check the notes and repeat the run','Delete every result','Change the toy car for all groups'],['Why keep the original result?','To show what happened and how they checked it','To pretend the short run never happened','To prove smooth flooring always stops cars']],
 ['Something in the results differs from the usual pattern.','Every result is missing from the record.','The speakers have not tried any test.'],[['surface','표면','the outside or top of something'],['repeat','반복하다','do something again']]);
add('event|사건|something that happens;paragraph|문단|sentences grouped around an idea;dialogue|대화|words spoken between characters;connect|연결하다|join ideas or things together',
 ['I use dialogue to show how characters feel.','Each paragraph helps connect one event to the next.'],
 'Tony writes about two friends whose kite gets caught in a tree. At first, his story jumps straight from the problem to the ending. His partner cannot understand how the friends solve it. Tony adds a paragraph describing their plan and uses dialogue to show their different ideas. He checks that each event connects clearly to the next. When his partner reads it again, the ending makes sense. Adding the missing link helps more than simply adding lots of extra words.',
 [['What was missing from the first draft?','How the friends planned to solve the problem','The names of every tree','A second unrelated ending'],['Why is the revised story clearer?','It connects the problem, plan and ending','It uses more words with no purpose','It removes every line of dialogue']],
 ['Characters’ spoken words reveal their feelings.','The speaker removes all characters from a story.','The speaker counts paragraphs without reading them.'],[['draft','초고','an early version of a piece of writing'],['revise','고쳐 쓰다','change work to make it better']]);
add('idea|생각|a thought or suggestion;example|예시|a specific case that helps explain;point|요점|the main thing someone wants to say;convince|설득하다|help someone believe an idea by giving reasons',
 ['An example can make my point easier to understand.','I use reasons to convince others to consider my idea.'],
 'Tony wants the class to create a quiet reading corner. His first point is that some readers find it hard to concentrate near noisy games. He gives an example from yesterday, when a classmate moved three times to find a quiet spot. Another student worries that the corner will take space from building activities. Tony listens and suggests trying a small corner for one week. He hopes to convince the class through reasons and a fair trial, rather than by speaking the loudest.',
 [['What example does Tony give?','A classmate moved three times to find quiet','Everyone stopped reading for a month','The classroom had no books'],['Why suggest a one-week trial?','To check the idea while considering the concern about space','To avoid listening to any other ideas','To keep the reading corner forever without discussion']],
 ['A specific case can help explain the main message.','An example always replaces every reason.','The speaker wants to hide the main message.'],[['concentrate','집중하다','give your attention to something'],['trial','시험 적용','trying an idea to see how it works']]);
add('progress|진전|improvement over time;strength|강점|something you can do well;target|목표|something you aim to achieve;future|미래|time that has not happened yet',
 ['My progress shows a strength I can build on.','I choose a small target for my future learning.'],
 'At the end of the course, Tony compares an early piece of writing with a recent one. He notices progress in connecting ideas and giving examples. That is now a strength, but he still wants to check punctuation more carefully. He chooses a clear target: reread one paragraph aloud before handing work in. Kai shares a different target for his own learning. They do not need identical goals. Both can use what they have learnt to plan a useful next step for the future.',
 [['What target does Tony choose?','Reread a paragraph aloud before handing work in','Use exactly the same target as Kai','Never look at an earlier piece of work'],['Why compare early and recent work?','To notice improvement and choose a useful next step','To decide that learning has ended','To prove every learner needs identical goals']],
 ['Improvement reveals something the speaker can develop further.','The speaker has decided never to learn again.','Every learner has the same strength.'],[['punctuation','문장 부호','marks that help make writing clear'],['goal','목표','something you want to achieve']]);
